### ISSUE TITLE
[BUG] Use failed, Why is this happening here?

### ISSUE THREAD

**Issue by git91895** [jhomlala/betterplayer#1065]
Failed to handle method call
E/MethodChannel#better_player_channel(25213): java.lang.NullPointerException: MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior.
E/MethodChannel#better_player_channel(25213): 	at f.a.a.a.n4.e.f(:174)
E/MethodChannel#better_player_channel(25213): 	at f.a.a.a.i4.n0$b.c(:186)
E/MethodChannel#better_player_channel(25213): 	at f.b.a.g.m(:430)
E/MethodChannel#better_player_channel(25213): 	at f.b.a.g.H(:196)
E/MethodChannel#better_player_channel(25213): 	at f.b.a.i.m(:277)
E/MethodChannel#better_player_channel(25213): 	at f.b.a.i.j(:151)
E/MethodChannel#better_player_channel(25213): 	at f.b.a.i.onMethodCall(:138)
E/MethodChannel#better_player_channel(25213): 	at i.a.e.a.k$a.a(:262)
E/MethodChannel#better_player_channel(25213): 	at i.a.d.b.f.e.k(:295)
E/MethodChannel#better_player_channel(25213): 	at i.a.d.b.f.e.l(:319)
E/MethodChannel#better_player_channel(25213): 	at i.a.d.b.f.e.m(Unknown Source:0)
E/MethodChannel#better_player_channel(25213): 	at i.a.d.b.f.c.run(Unknown Source:12)
E/MethodChannel#better_player_channel(25213): 	at android.os.Handler.handleCallback(Handler.java:900)
E/MethodChannel#better_player_channel(25213): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/MethodChannel#better_player_channel(25213): 	at android.os.Looper.loop(Looper.java:219)
E/MethodChannel#better_player_channel(25213): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/MethodChannel#better_player_channel(25213): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#better_player_channel(25213): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#better_player_channel(25213): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/flutter (25213): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior., null, java.lang.NullPointerException: MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior.
E/flutter (25213): 	at f.a.a.a.n4.e.f(:174)
E/flutter (25213): 	at f.a.a.a.i4.n0$b.c(:186)
E/flutter (25213): 	at f.b.a.g.m(:430)
E/flutter (25213): 	at f.b.a.g.H(:196)
E/flutter (25213): 	at f.b.a.i.m(:277)
E/flutter (25213): 	at f.b.a.i.j(:151)
E/flutter (25213): 	at f.b.a.i.onMethodCall(:138)
E/flutter (25213): 	at i.a.e.a.k$a.a(:262)
E/flutter (25213): 	at i.a.d.b.f.e.k(:295)
E/flutter (25213): 	at i.a.d.b.f.e.l(:319)
E/flutter (25213): 	at i.a.d.b.f.e.m(Unknown Source:0)
E/flutter (25213): 	at i.a.d.b.f.c.run(Unknown Source:12)
E/flutter (25213): 	at android.os.Handler.handleCallback(Handler.java:900)
E/flutter (25213): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/flutter (25213): 	at android.os.Looper.loop(Looper.java:219)
E/flutter (25213): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/flutter (25213): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (25213): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (25213): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/flutter (25213): )
E/flutter (25213): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (25213): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (25213): <asynchronous suspension>
E/flutter (25213): #2      MethodChannelVideoPlayer.setDataSource (package:better_player/src/video_player/method_channel_video_player.dart:118:5)
E/flutter (25213): <asynchronous suspension>
E/flutter (25213): #3      VideoPlayerController._setDataSource (package:better_player/src/video_player/video_player.dart:408:5)
E/flutter (25213): <asynchronous suspension>
E/flutter (25213): #4      BetterPlayerController._setupDataSource (package:better_player/src/core/better_player_controller.dart:444:9)
E/flutter (25213): <asynchronous suspension>
E/flutter (25213): #5      BetterPlayerController.setupDataSource (package:better_player/src/core/better_player_controller.dart:274:5)
E/flutter (25213): <asynchronous suspension>

**Comment by chornthorn** [comment]
I have the same problem. Please ower help check it.

**Comment by git91895** [comment]
> I have the same problem. Please ower help check it.

不能和video_player一起用,原因不太清楚.

**Comment by 18312259738** [comment]
请问解决了这个问题了吗？我发现 better_player: ^0.0.82之后都会有这个问题

**Comment by thijmenverkerk** [comment]
I am running into the same issue. Would really like to know what is going on here.

**Comment by Musfick** [comment]
i am facing same issue. any help would be appreciated

**Comment by git91895** [comment]
#1057

**Comment by hassanyounas79** [comment]
"MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior."

**Comment by Karin-1k** [comment]
the same issue

**Comment by jhomlala** [comment]
Fixed in latest release.
