### ISSUE TITLE
[BUG] m3u8  Abnormal playback

### ISSUE THREAD

**Issue by as3635629** [jhomlala/betterplayer#1068]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: RangeError (millisecondsSinceEpoch): Invalid value: Not in inclusive range -8640000000000000..8640000000000000: 9223372036854733809
E/flutter ( 8615): #0      RangeError.checkValueInInterval (dart:core/errors.dart:300:7)
E/flutter ( 8615): #1      DateTime._validateMilliseconds (dart:core-patch/date_patch.dart:63:18)
E/flutter ( 8615): #2      new DateTime.fromMillisecondsSinceEpoch (dart:core-patch/date_patch.dart:42:13)
E/flutter ( 8615): #3      MethodChannelVideoPlayer.getAbsolutePosition (package:better_player/src/video_player/method_channel_video_player.dart:222:21)
E/flutter ( 8615): <asynchronous suspension>
E/flutter ( 8615): #4      VideoPlayerController._applyPlayPause.<anonymous closure> (package:better_player/src/video_player/video_player.dart:472:49)
E/flutter ( 8615): <asynchronous suspension>
E/flutter ( 8615): 
I/AudioTrack( 8615): recheck for pg, sessionid : 265

**Comment by okmsbun** [comment]
I am also facing the same problem. I'm encountering this issue with some of the broadcasts that have short **duration**_(videoPlayerController?.value.duration)_ in live broadcasts. I can't catch it with catch.
