### ISSUE TITLE
Google drive's private url can't play.

### ISSUE THREAD

**Issue by waihanko** [jhomlala/betterplayer#1074]
In my app, I already integrated with google login and I successfully accessed my google drive folder and video files(mp4). But better player can play public video by modified url like this `https://drive.google.com/uc?id=my_video_file_id`. 
I want to develop an app like **Nplayer** or **Kudoplayer**.

For private url, following log print.

`E/libc    (22596): Access denied finding property "ro.vendor.df.effect.conflict"
E/libc    (22596): Access denied finding property "ro.vendor.knock.type"
E/ExoPlayerImplInternal(22596): Playback error
E/ExoPlayerImplInternal(22596):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(22596):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
E/ExoPlayerImplInternal(22596):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
E/ExoPlayerImplInternal(22596):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(22596):       at android.os.Looper.loop(Looper.java:236)
E/ExoPlayerImplInternal(22596):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(22596):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.
E/ExoPlayerImplInternal(22596):       at com.google.android.exoplayer2.source.BundledExtractorsAdapter.init(BundledExtractorsAdapter.java:92)
E/ExoPlayerImplInternal(22596):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1020)
E/ExoPlayerImplInternal(22596):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
E/ExoPlayerImplInternal(22596):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(22596):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(22596):       at java.lang.Thread.run(Thread.java:923)
E/flutter (22596): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: Source error, , null)
`

**Comment by jhomlala** [comment]
After reviewing this, the described behavior is working as intended. A private Google Drive URL returns an HTML login page rather than a video stream if you don't provide the correct authentication headers. ExoPlayer cannot parse HTML, hence the `UnrecognizedInputFormatException`. To play private videos, you need to provide a direct video stream URL and pass the required authentication headers (such as a Bearer token) using the `headers` property in `BetterPlayerDataSource`. Closing this issue — feel free to re-open if you have further questions.
