### ISSUE TITLE
i found the error in latest version of better_player 0.0.83

### ISSUE THREAD

**Issue by sachin468** [jhomlala/betterplayer#1093]
E/MethodChannel#better_player_channel( 8270): 	at com.jhomlala.better_player.BetterPlayer.setDataSource(BetterPlayer.kt:196)
E/MethodChannel#better_player_channel( 8270): 	at com.jhomlala.better_player.BetterPlayerPlugin.setDataSource(BetterPlayerPlugin.kt:277)
E/MethodChannel#better_player_channel( 8270): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:151)
E/MethodChannel#better_player_channel( 8270): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:138)
E/MethodChannel#better_player_channel( 8270): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#better_player_channel( 8270): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#better_player_channel( 8270): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#better_player_channel( 8270): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#better_player_channel( 8270): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#better_player_channel( 8270): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#better_player_channel( 8270): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#better_player_channel( 8270): 	at android.app.ActivityThread.main(ActivityThread.java:6692)
E/MethodChannel#better_player_channel( 8270): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#better_player_channel( 8270): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#better_player_channel( 8270): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by priyankgandhi0** [comment]
- update latest exoPlayer version in better_player build.gradle currently 2.18.1 is latest version.
- sync and build project
- comment all error lines in better_player module's BetterPlayer.kt

**Comment by dipak1267** [comment]
- update latest exoPlayer version in better_player build.gradle currently 2.18.1 is latest version.
- sync and build project
- comment all error lines in better_player module's BetterPlayer.kt

**Comment by NilkanthMF** [comment]
Hi @sachin468 

Try this package version because I got same error 
it's working fine in iOS but show this error in android 

try this maybe it would be helpful

```
better_player: ^0.0.82
video_player: 2.1.12
```

**Comment by jhomlala** [comment]
Please use latest Better Player version. It should be fixed.
