### ISSUE TITLE
not able to play video on some devices.

### ISSUE THREAD

**Issue by vikrantyadav7** [jhomlala/betterplayer#1101]
Video is playing on some android tv, but is not on some tv.

- Version: 0.0.83

**Smartphone (please complete the following information):**
 - Device: android tv
 - OS: 10

here is console log:
here is the source url : https://dl.dropboxusercontent.com/s/xjloecedqsrhkk6/Moonfall%20%282022%29%201080p%2010bit%20BluRay%20x265%20HEVC%20%5BOrg%20AMZN%20Hindi%20DDP%202.0%20_224Kbps%2B%20English%20AAC%207.1%5D%20ESub%20_%20Tigole%20%281%29.mkv?dl=0
``` 
NoSupport [codec.profileLevel, hvc1.2.4.L120.90, video/hevc] [c2.android.hevc.decoder, video/hevc] [emulator64_arm64, sdk_google_atv64_amati_arm64, Google, 31]
D/MediaCodecInfo(24210): NoSupport [codec.profileLevel, hvc1.2.4.L120.90, video/hevc] [c2.android.hevc.decoder, video/hevc] [emulator64_arm64, sdk_google_atv64_amati_arm64, Google, 31]
I/DMCodecAdapterFactory(24210): Creating an asynchronous MediaCodec adapter for track type video
D/CCodec  (24210): allocate(c2.android.hevc.decoder)
I/CCodec  (24210): setting up 'default' as default (vendor) store
I/CCodec  (24210): Created component [c2.android.hevc.decoder]
D/CCodecConfig(24210): read media type: video/hevc
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: algo.buffers.pool-ids.values
D/ReflectedParamUpdater(24210): ignored struct field coded.color-format.locations
D/CCodecConfig(24210): ignoring local param raw.size (0xd2001800) as it is already supported
D/CCodecConfig(24210): ignoring local param default.color (0x5200180b) as it is already supported
D/ReflectedParamUpdater(24210): ignored struct field raw.hdr-static-info.mastering
I/CCodecConfig(24210): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig(24210): c2 config diff is Dict {
D/CCodecConfig(24210):   c2::u32 coded.pl.level = 24584
D/CCodecConfig(24210):   c2::u32 coded.pl.profile = 24576
D/CCodecConfig(24210):   c2::u32 coded.vui.color.matrix = 0
D/CCodecConfig(24210):   c2::u32 coded.vui.color.primaries = 0
D/CCodecConfig(24210):   c2::u32 coded.vui.color.range = 2
D/CCodecConfig(24210):   c2::u32 coded.vui.color.transfer = 0
D/CCodecConfig(24210):   c2::u32 default.color.matrix = 0
D/CCodecConfig(24210):   c2::u32 default.color.primaries = 0
D/CCodecConfig(24210):   c2::u32 default.color.range = 0
D/CCodecConfig(24210):   c2::u32 default.color.transfer = 0
D/CCodecConfig(24210):   c2::u32 input.buffers.max-size.value = 61440
D/CCodecConfig(24210):   c2::u32 input.delay.value = 0
D/CCodecConfig(24210):   string input.media-type.value = "video/hevc"
D/CCodecConfig(24210):   c2::u32 output.delay.value = 8
D/CCodecConfig(24210):   string output.media-type.value = "video/raw"
D/CCodecConfig(24210):   c2::u32 raw.color.matrix = 0
D/CCodecConfig(24210):   c2::u32 raw.color.primaries = 0
D/CCodecConfig(24210):   c2::u32 raw.color.range = 2
D/CCodecConfig(24210):   c2::u32 raw.color.transfer = 0
D/CCodecConfig(24210):   c2::u32 raw.max-size.height = 240
D/CCodecConfig(24210):   c2::u32 raw.max-size.width = 320
D/CCodecConfig(24210):   c2::u32 raw.pixel-format.value = 35
D/CCodecConfig(24210):   c2::i32 raw.rotation.flip = 0
D/CCodecConfig(24210):   c2::i32 raw.rotation.value = 0
D/CCodecConfig(24210):   c2::u32 raw.sar.height = 1
D/CCodecConfig(24210):   c2::u32 raw.sar.width = 1
D/CCodecConfig(24210):   c2::u32 raw.size.height = 240
D/CCodecConfig(24210):   c2::u32 raw.size.width = 320
D/CCodecConfig(24210):   c2::
W/ColorUtils(24210): expected specified color aspects (2:0:0:0)
I/MediaCodec(24210): MediaCodec will operate in async mode
D/SurfaceUtils(24210): connecting to surface 0xb400007b95f58dc0, reason connectToSurface
I/MediaCodec(24210): [c2.android.hevc.decoder] setting surface generation to 24791047
D/SurfaceUtils(24210): disconnecting from surface 0xb400007b95f58dc0, reason connectToSurface(reconnect)
D/SurfaceUtils(24210): connecting to surface 0xb400007b95f58dc0, reason connectToSurface(reconnect)
D/CCodec  (24210): [c2.android.hevc.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(24210): no c2 equivalents for color-standard
D/CCodecConfig(24210): no c2 equivalents for native-window
D/CCodecConfig(24210): no c2 equivalents for flags
D/CCodecConfig(24210): config failed => CORRUPTED
D/CCodecConfig(24210): c2 config diff is   c2::u32 default.color.matrix = 1
D/CCodecConfig(24210):   c2::u32 default.color.primaries = 1
D/CCodecConfig(24210):   c2::u32 default.color.range = 2
D/CCodecConfig(24210):   c2::u32 default.color.transfer = 3
D/CCodecConfig(24210):   c2::u32 input.buffers.max-size.value = 1198080
D/CCodecConfig(24210):   c2::u32 raw.max-size.height = 804
D/CCodecConfig(24210):   c2::u32 raw.max-size.width = 1920
D/CCodecConfig(24210):   c2::u32 raw.size.height = 804
D/CCodecConfig(24210):   c2::u32 raw.size.width = 1920
W/Codec2Client(24210): query -- param skipped: index = 1107298332.
D/CCodec  (24210): client requested max input size 578880, which is smaller than what component recommended (1198080); overriding with component recommendation.
W/CCodec  (24210): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (24210): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (24210):   int32_t height = 804
D/CCodec  (24210):   int32_t level = 65536
D/CCodec  (24210):   int32_t max-input-size = 1198080
D/CCodec  (24210):   string mime = "video/hevc"
D/CCodec  (24210):   int32_t profile = 1
D/CCodec  (24210):   int32_t width = 1920
D/CCodec  (24210):   Rect crop(0, 0, 1919, 803)
D/CCodec  (24210): }
D/CCodec  (24210): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (24210):   int32_t android._color-format = 2135033992
D/CCodec  (24210):   int32_t android._video-scaling = 1
D/CCodec  (24210):   int32_t rotation-degrees = 0
D/CCodec  (24210):   int32_t color-standard = 1
D/CCodec  (24210):   int32_t color-range = 2
D/CCodec  (24210):   int32_t color-transfer = 3
D/CCodec  (24210):   int32_t sar-height = 1
D/CCodec  (24210):   int32_t sar-width = 1
D/CCodec  (24210):   Rect crop(0, 0, 1919, 803)
D/CCodec  (24210):   int32_t width = 1920
D/CCodec  (24210):   int32_t height = 804
D/CCodec  (24210):   int32_t max-height = 804
D/CCodec  (24210):   int32_t max-width = 1920
D/CCodec  (24210):   string mime = "video/raw"
D/CCodec  (24210):   int32_t android._dataspace = 260
D/CCodec  (24210):   int32_t color-format = 2130708361
D/CCodec  (24210): }
I/CCodecConfig(24210): query failed after returning 12 values (BAD_INDEX)
D/CCodecConfig(24210): c2 config diff is   c2::u32 raw.color.matrix = 1
D/CCodecConfig(24210):   c2::u32 raw.color.primaries = 1
D/CCodecConfig(24210):   c2::u32 raw.color.transfer = 3
D/MediaCodec(24210): keep callback message for reclaim
W/Codec2Client(24210): query -- param skipped: index = 1342179345.
W/Codec2Client(24210): query -- param skipped: index = 2415921170.
W/Codec2Client(24210): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel(24210): [c2.android.hevc.decoder#548] Created input block pool with allocatorID 16 => poolID 24 - OK (0)
D/CCodecBufferChannel(24210): [c2.android.hevc.decoder#548] Query output surface allocator returned 0 params => BAD_INDEX (6)
I/CCodecBufferChannel(24210): [c2.android.hevc.decoder#548] Created output block pool with allocatorID 18 => poolID 79 - OK
D/CCodecBufferChannel(24210): [c2.android.hevc.decoder#548] Configured output block pool ids 79 => OK
D/Codec2-OutputBufferQueue(24210): C2SurfaceSyncMemory created 20(20)
D/Codec2-OutputBufferQueue(24210): remote graphic buffer migration 0/0
D/Codec2Client(24210): setOutputSurface -- failed to set consumer usage (6/BAD_INDEX)
D/Codec2Client(24210): setOutputSurface -- generation=24791047 consumer usage=0x900 sync
D/Codec2Client(24210): Surface configure completed
D/BufferPoolAccessor2.0(24210): bufferpool2 0xb400007af5e5ab68 : 0(0 size) total buffers - 0(0 size) used buffers - 2/7 (recycle/alloc) - 1/2 (fetch/transfer)
D/BufferPoolAccessor2.0(24210): Destruction - bufferpool2 0xb400007af5e5ab68 cached: 0/0M, 0/0% in use; allocs: 7, 29% recycled; transfers: 2, 50% unfetched
D/BufferPoolAccessor2.0(24210): bufferpool2 0xb400007af5e8b908 : 0(0 size) total buffers - 0(0 size) used buffers - 6/11 (recycle/alloc) - 1/2 (fetch/transfer)
D/BufferPoolAccessor2.0(24210): Destruction - bufferpool2 0xb400007af5e8b908 cached: 0/0M, 0/0% in use; allocs: 11, 55% recycled; transfers: 2, 50% unfetched
I/DMCodecAdapterFactory(24210): Creating an asynchronous MediaCodec adapter for track type audio
D/CCodec  (24210): allocate(c2.android.aac.decoder)
I/CCodec  (24210): setting up 'default' as default (vendor) store
I/CCodec  (24210): Created component [c2.android.aac.decoder]
D/CCodecConfig(24210): read media type: audio/mp4a-latm
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(24210): extent() != 1 for single value type: algo.buffers.pool-ids.values
D/CCodecBufferChannel(24210): [c2.android.hevc.decoder#548] work failed to complete: 14
E/MediaCodec(24210): Codec reported err 0xe, actionCode 0, while in state 6/STARTED
D/SurfaceUtils(24210): disconnecting from surface 0xb400007b95f58dc0, reason disconnectFromSurface
I/CCodecConfig(24210): query failed after returning 19 values (BAD_INDEX)
D/CCodecConfig(24210): c2 config diff is Dict {
D/CCodecConfig(24210):   c2::u32 coded.aac-packaging.value = 0
D/CCodecConfig(24210):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(24210):   c2::u32 coded.pl.level = 0
D/CCodecConfig(24210):   c2::u32 coded.pl.profile = 8192
D/CCodecConfig(24210):   c2::i32 coding.drc.album-mode.value = 0
D/CCodecConfig(24210):   c2::float coding.drc.attenuation-factor.value = 1
D/CCodecConfig(24210):   c2::float coding.drc.boost-factor.value = 1
D/CCodecConfig(24210):   c2::i32 coding.drc.compression-mode.value = 3
D/CCodecConfig(24210):   c2::i32 coding.drc.effect-type.value = 3
D/CCodecConfig(24210):   c2::float coding.drc.encoded-level.value = 0.25
D/CCodecConfig(24210):   c2::float coding.drc.reference-level.value = -16
D/CCodecConfig(24210):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(24210):   c2::u32 input.delay.value = 0
D/CCodecConfig(24210):   string input.media-type.value = "audio/mp4a-latm"
D/CCodecConfig(24210):   c2::u32 output.delay.value = 2
D/CCodecConfig(24210):   c2::float output.drc.output-loudness.value = 0.25
D/CCodecConfig(24210):   string output.media-type.value = "audio/raw"
D/CCodecConfig(24210):   c2::u32 raw.channel-count.value = 1
D/CCodecConfig(24210):   c2::u32 raw.max-channel-count.value = 8
D/CCodecConfig(24210):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(24210): }
I/MediaCodec(24210): MediaCodec will operate in async mode
D/CCodec  (24210): [c2.android.aac.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(24210): no c2 equivalents for flags
D/CCodecConfig(24210): c2 config diff is   c2::u32 raw.sample-rate.value = 48000
W/Codec2Client(24210): query -- param skipped: index = 1107298332.
D/CCodec  (24210): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (24210):   int32_t aac-drc-album-mode = 0
D/CCodec  (24210):   int32_t aac-drc-boost-level = 127
D/CCodec  (24210):   int32_t aac-drc-cut-level = 127
D/CCodec  (24210):   int32_t aac-drc-effect-type = 3
D/CCodec  (24210):   int32_t aac-encoded-target-level = -1
D/CCodec  (24210):   int32_t aac-max-output-channel_count = 8
D/CCodec  (24210):   int32_t aac-target-ref-level = 64
D/CCodec  (24210):   int32_t bitrate = 64000
D/CCodec  (24210):   int32_t channel-count = 1
D/CCodec  (24210):   int32_t level = 0
D/CCodec  (24210):   int32_t max-input-size = 8192
D/CCodec  (24210):   string mime = "audio/mp4a-latm"
D/CCodec  (24210):   int32_t profile = 2
D/CCodec  (24210):   int32_t sample-rate = 48000
D/CCodec  (24210): }
D/CCodec  (24210): setup formats output: AMessage(what = 0x00000000) = {
D/CCodec  (24210):   int32_t aac-drc-album-mode = 0
D/CCodec  (24210):   int32_t aac-drc-boost-level = 127
D/CCodec  (24210):   int32_t aac-drc-cut-level = 127
D/CCodec  (24210):   int32_t aac-drc-effect-type = 3
D/CCodec  (24210):   int32_t aac-drc-output-loudness = -1
D/CCodec  (24210):   int32_t aac-encoded-target-level = -1
D/CCodec  (24210):   int32_t aac-max-output-channel_count = 8
D/CCodec  (24210):   int32_t aac-target-ref-level = 64
D/CCodec  (24210):   int32_t channel-count = 1
D/CCodec  (24210):   string mime = "audio/raw"
D/CCodec  (24210):   int32_t sample-rate = 48000
D/CCodec  (24210): }
I/CCodecConfig(24210): query failed after returning 19 values (BAD_INDEX)
D/MediaCodec(24210): keep callback message for reclaim
W/Codec2Client(24210): query -- param skipped: index = 1342179345.
W/Codec2Client(24210): query -- param skipped: index = 2415921170.
W/Codec2Client(24210): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel(24210): [c2.android.aac.decoder#403] Created input block pool with allocatorID 16 => poolID 25 - OK (0)
I/CCodecBufferChannel(24210): [c2.android.aac.decoder#403] Created output block pool with allocatorID 16 => poolID 80 - OK
D/CCodecBufferChannel(24210): [c2.android.aac.decoder#403] Configured output block pool ids 80 => OK
E/MediaCodecVideoRenderer(24210): Video codec error
E/MediaCodecVideoRenderer(24210):   android.media.MediaCodec$CodecException: Error 0xe
D/MediaCodecInfo(24210): NoSupport [codec.profileLevel, hvc1.2.4.L120.90, video/hevc] [c2.android.hevc.decoder, video/hevc] [emulator64_arm64, sdk_google_atv64_amati_arm64, Google, 31]
E/ExoPlayerImplInternal(24210): Playback error
E/ExoPlayerImplInternal(24210):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/hevc, hvc1.2.4.L120.90, -1, und, [1920, 804, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
E/ExoPlayerImplInternal(24210):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(24210):       at android.os.Looper.loopOnce(Looper.java:201)
E/ExoPlayerImplInternal(24210):       at android.os.Looper.loop(Looper.java:288)
E/ExoPlayerImplInternal(24210):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(24210):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.hevc.decoder
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
E/ExoPlayerImplInternal(24210):       ... 4 more
E/ExoPlayerImplInternal(24210):   Caused by: android.media.MediaCodec$CodecException: Error 0xe
E/ExoPlayerImplInternal(24210): Disable failed.
E/ExoPlayerImplInternal(24210):   java.lang.IllegalStateException
E/ExoPlayerImplInternal(24210):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal(24210):       at android.media.MediaCodec.flush(MediaCodec.java:2350)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:237)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:864)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:857)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:710)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:561)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:186)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1671)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1411)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1374)
E/ExoPlayerImplInternal(24210):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:591)
E/ExoPlayerImplInternal(24210):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(24210):       at android.os.Looper.loopOnce(Looper.java:201)
E/ExoPlayerImplInternal(24210):       at android.os.Looper.loop(Looper.java:288)
E/ExoPlayerImplInternal(24210):       at android.os.HandlerThread.run(HandlerThread.java:67)
D/MediaCodec(24210): keep callback message for reclaim
I/CCodecConfig(24210): query failed after returning 19 values (BAD_INDEX)
W/Codec2Client(24210): query -- param skipped: index = 1342179345.
W/Codec2Client(24210): query -- param skipped: index = 2415921170.
W/Codec2Client(24210): query -- param skipped: index = 1610614798.
D/CCodecBufferChannel(24210): [c2.android.hevc.decoder#548] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(24210): [c2.android.hevc.decoder#548] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(24210): [c2.android.hevc.decoder#548] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(24210): [c2.android.aac.decoder#403] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(24210): [c2.android.aac.decoder#403] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(24210): [c2.android.aac.decoder#403] MediaCodec discarded an unknown buffer
D/CCodecBufferChannel(24210): [c2.android.aac.decoder#403] MediaCodec discarded an unknown buffer
E/BufferQueueProducer(24210): [SurfaceTexture-0-24210-4](id:5e9200000008,api:0,p:-1,c:24210) cancelBuffer: BufferQueue has no connected producer
I/hw-BpHwBinder(24210): onLastStrongRef automatically unlinking death recipients
I/hw-BpHwBinder(24210): onLastStrongRef automatically unlinking death recipients
E/BufferQueueProducer(24210): [SurfaceTexture-0-24210-4](id:5e9200000008,api:0,p:-1,c:24210) detachBuffer: BufferQueue has no connected producer
I/flutter (24210): PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/hevc, hvc1.2.4.L120.90, -1, und, [1920, 804, -1.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, , null)
I/ExoPlayerImpl(24210): Release ad591c2 [ExoPlayerLib/2.17.1] [emulator64_arm64, sdk_google_atv64_amati_arm64, Google, 31] [goog.exo.core, goog.exo.exoplayer, goog.exo.decoder, goog.exo.datasource, goog.exo.extractor]
D/BufferPoolAccessor2.0(24210): bufferpool2 0xb400007af5e9a4e8 : 0(0 size) total buffers - 0(0 size) used buffers - 2/7 (recycle/alloc) - 1/2 (fetch/transfer)
D/BufferPoolAccessor2.0(24210): evictor expired: 3, evicted: 1
D/BufferPoolAccessor2.0(24210): bufferpool2 0xb400007af5eb4528 : 0(0 size) total buffers - 0(0 size) used buffers - 6/11 (recycle/alloc) - 1/2 (fetch/transfer)
D/BufferPoolAccessor2.0(24210): evictor expired: 1, evicted: 1
```

**Comment by rjkolli7** [comment]
Am also playing same issue. 

Player Exception :: Video player had error pO.n: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/ avc, avc1.4D4028, -1, null, [1920, 1080, 29.99964], -1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES

Am using Android TV (Brand: TPL) with Android 9 OS.  Application is running at client location and could not provide much logs for error.

Does anyone have solution for this?

**Comment by PriyankP99** [comment]
I'm getting similar issue on Android 14 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640032, -1, null, [1440, 2734, 30.000002], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES, , null)
