### ISSUE TITLE
better player have some issue since 1 nov. video not playe 

### ISSUE THREAD

**Issue by Karanvthakur148** [jhomlala/betterplayer#1116]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**

**To Reproduce**

**Example code*
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

**Expected behavior**

**Screenshots**

**Flutter doctor**
Please add flutter doctor output here.

**Better Player version**
- Version:

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SamerCat** [comment]
same for me on version 0.0.82

**Comment by Tha14** [comment]
@Karanvthakur148 Can you please edit the issue content with the required information? It helps a lot to debug this.
Also, I have the same problem and it appears to be happening because of some other dependency. I'm still using an outdated pubspec.lock but have not pinpointed the exact one yet.

**Comment by Tha14** [comment]
@jhomlala 
I've caught the error with catcher:
```
PlatformException(error, MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior., null, java.lang.NullPointerException: MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior. at g2.a.f(SourceFile) at j1.l0$b.d(SourceFile) at y2.d.p(SourceFile) at y2.d.H(SourceFile) at y2.h.s(SourceFile) at y2.h.p(SourceFile) at y2.h.C(SourceFile) at a4.k$a.a(SourceFile) at n3.c.l(SourceFile) at n3.c.m(SourceFile) at n3.c.i(SourceFile) at n3.b.run(SourceFile) at android.os.Handler.handleCallback(Handler.java:751) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6198) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) )

Stack trace:

#0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
#1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296)
<asynchronous suspension>
#2 MethodChannelVideoPlayer.setDataSource (package:better_player/src/video_player/method_channel_video_player.dart:118)
<asynchronous suspension>
#3 VideoPlayerController._setDataSource (package:better_player/src/video_player/video_player.dart:408)
<asynchronous suspension>
#4 BetterPlayerController._setupDataSource (package:better_player/src/core/better_player_controller.dart:444)
<asynchronous suspension>
#5 BetterPlayerController.setupDataSource (package:better_player/src/core/better_player_controller.dart:274)
<asynchronous suspension>


Device parameters:

id: QP1A.190711.020
board: exynos9810
bootloader: G9550ZHU1AQEE
brand: samsung
device: star2lte
display: star2ltexx-user 7.1.2 QP1A.190711.020 700210421 release-keys
fingerprint: samsung/star2ltexx/star2lte:7.1.2/QP1A.190711.020/700210421:user/release-keys
hardware: samsungexynos9810
host: SWDI2014
isPhysicalDevice: true
manufacturer: samsung
model: SM-G965N
product: star2ltexx
tags: release-keys
type: user
versionBaseOs:
versionCodename: REL
versionIncremental: 700210421
versionPreviewSdk: 0
versionRelease: 7.1.2
versionSdk: 25
versionSecurityPatch: 2017-10-05
```

**Comment by Tha14** [comment]
#1113  Same problem here.

**Comment by jhomlala** [comment]
This has been fixed. Please update to the latest version.
