### ISSUE TITLE
Failed to handle method call[BUG]

### ISSUE THREAD

**Issue by xTanveerAhmad** [jhomlala/betterplayer#1119]
**Code:**
class VideoPlayerPage2 extends StatefulWidget {
  final MVideo video;
  const VideoPlayerPage2({Key? key,required this.video}) : super(key: key);
  @override
  State<VideoPlayerPage2> createState() => _VideoPlayerPage2State();
}

class _VideoPlayerPage2State extends State<VideoPlayerPage2> {
  late BetterPlayerController _betterPlayerController;
  late BetterPlayerDataSource betterPlayerDataSource;

  @override
  void initState() {
    super.initState();
    setState(() {
      betterPlayerDataSource = BetterPlayerDataSource(BetterPlayerDataSourceType.file, widget.video.path);
    });
    _betterPlayerController = BetterPlayerController( const BetterPlayerConfiguration(),
        betterPlayerDataSource: betterPlayerDataSource);
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AspectRatio(
        aspectRatio: 16 / 9,
        child: BetterPlayer(
          controller: _betterPlayerController,
        ),
      ),
    );
  }
}
**Bug:**
MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
E/flutter (20832): <asynchronous suspension>
E/flutter (20832): #2      MethodChannelVideoPlayer.setDataSource (package:better_player/src/video_player/method_channel_video_player.dart:118:5)
E/flutter (20832): <asynchronous suspension>
E/flutter (20832): #3      VideoPlayerController._setDataSource (package:better_player/src/video_player/video_player.dart:408:5)
E/flutter (20832): <asynchronous suspension>
E/flutter (20832): #4      BetterPlayerController._setupDataSource (package:better_player/src/core/better_player_controller.dart:485:9)
E/flutter (20832): <asynchronous suspension>
E/flutter (20832): #5      BetterPlayerController.setupDataSource (package:better_player/src/core/better_player_controller.dart:274:5)
E/flutter (20832): <asynchronous suspension>

**Comment by saheel-texolworld** [comment]
pls remove all other video player

**Comment by jhomlala** [comment]
Please update to the latest Better Player version, this might fix your issue.
