### ISSUE TITLE
 Unhandled Exception: PlatformException(error, MediaSource.

### ISSUE THREAD

**Issue by Deepak96321** [jhomlala/betterplayer#1147]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(error, MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior., null, java.lang.NullPointerException: MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior.
E/flutter (16072): 	at b9.a.f()
E/flutter (16072): 	at e8.j0$b.d()
E/flutter (16072): 	at com.jhomlala.better_player.a.p()
E/flutter (16072): 	at com.jhomlala.better_player.a.H()
E/flutter (16072): 	at cd.g.t()
E/flutter (16072): 	at cd.g.q()
E/flutter (16072): 	at cd.g.f()
E/flutter (16072): 	at te.k$a.a()
E/flutter (16072): 	at ge.c.l()
E/flutter (16072): 	at ge.c.m()
E/flutter (16072): 	at ge.c.i()
E/flutter (16072): 	at ge.b.run()
E/flutter (16072): 	at android.os.Handler.handleCallback(Handler.java:754)
E/flutter (16072): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/flutter (16072): 	at android.os.Looper.loop(Looper.java:163)
E/flutter (16072): 	at android.app.ActivityThread.main(ActivityThread.java:6238)
E/flutter (16072): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (16072): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
E/flutter (16072): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
E/flutter (16072): )
E/flutter (16072): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607)
E/flutter (16072): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167)
E/flutter (16072): <asynchronous suspension>
E/flutter (16072): #2      MethodChannelVideoPlayer.setDataSource (package:better_player/src/video_player/method_channel_video_player.dart:118)
E/flutter (16072): <asynchronous suspension>
E/flutter (16072): #3      VideoPlayerController._setDataSource (package:better_player/src/video_player/video_player.dart:408)
E/flutter (16072): <asynchronous suspension>
E/flutter (16072): #4      BetterPlayerController._setupDataSource (package:better_player/src/core/better_player_controller.dart:444)
E/flutter (16072): <asynchronous suspension>
E/flutter (16072): #5      BetterPlayerController.setupDataSource (package:better_player/src/core/better_player_controller.dart:274)
E/flutter (16072): <asynchronous suspension>
E/flutter (16072):

**Comment by gideonoyekale** [comment]
any solutions yet to this issue?

**Comment by iranandroid** [comment]
i have same problem
any solutions yet to this issue?

**Comment by giroprotagonist** [comment]
Same problem, not sure when it cropped up, I had to remove videoplayer and it started working again, definitely a conflict between the packages. Too bad as I need both plugin's in my project at the moment.

**Comment by DurgeshSawantWYLD** [comment]
@jhomlala, people have already added a fix PR's as well, please update the package

**Comment by jhomlala** [comment]
Fixed in 0.1.0.
