### ISSUE TITLE
i am facing app crash how to fix this problem video player is not working please give me any solution

### ISSUE THREAD

**Issue by MayankSarathe** [jhomlala/betterplayer#1219]
[GETX] Instance "VideoStateController" has been created with tag "[#ab06d]"
[GETX] Instance "VideoStateController" with tag "[#ab06d]" has been initialized
W/ratelimit( 7708): Single process limit 250/s drop 1515 lines.
I/ExoPlayerImpl( 7708): Init df9354d [ExoPlayerLib/2.18.7] [2034, V2069, vivo, 30]
E/AndroidRuntime( 7708): FATAL EXCEPTION: main
E/AndroidRuntime( 7708): Process: com.digitalshiksha.app, PID: 7708
E/AndroidRuntime( 7708): java.lang.NoSuchMethodError: No virtual method buildOrThrow()Lcom/google/common/collect/ImmutableMap; in class Lcom/google/common/collect/ImmutableMap$Builder; or its super classes (declaration of 'com.google.common.collect.ImmutableMap$Builder' appears in /data/app/~~Gd2sK_j1GKF3lt9xLdSVpQ==/com.digitalshiksha.app-NS-bpBqp4iF2a5bE1w37dA==/base.apk!classes6.dex)
E/AndroidRuntime( 7708): 	at com.google.android.exoplayer2.audio.AudioCapabilities.<clinit>(AudioCapabilities.java:75)
E/AndroidRuntime( 7708): 	at com.google.android.exoplayer2.audio.DefaultAudioSink$Builder.<init>(DefaultAudioSink.java:230)
E/AndroidRuntime( 7708): 	at com.google.android.exoplayer2.DefaultRenderersFactory.buildAudioSink(DefaultRenderersFactory.java:626)
E/AndroidRuntime( 7708): 	at com.google.android.exoplayer2.DefaultRenderersFactory.createRenderers(DefaultRenderersFactory.java:305)
E/AndroidRuntime( 7708): 	at com.google.android.exoplayer2.ExoPlayerImpl.<init>(ExoPlayerImpl.java:244)
E/AndroidRuntime( 7708): 	at com.google.android.exoplayer2.ExoPlayer$Builder.build(ExoPlayer.java:1131)
E/AndroidRuntime( 7708): 	at com.jhomlala.better_player.BetterPlayer.<init>(BetterPlayer.kt:111)
E/AndroidRuntime( 7708): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:118)
E/AndroidRuntime( 7708): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 7708): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 7708): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 7708): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 7708): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 7708): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7708): 	at android.os.Looper.loop(Looper.java:257)
E/AndroidRuntime( 7708): 	at android.app.ActivityThread.main(ActivityThread.java:8183)
E/AndroidRuntime( 7708): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7708): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
E/AndroidRuntime( 7708): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)
I/Process ( 7708): Sending signal. PID: 7708 SIG: 9
Lost connection to device.

**Comment by jhomlala** [comment]
Fixed in 0.1.0.
