### ISSUE TITLE
Android is not play[BUG]

### ISSUE THREAD

**Issue by 1771893348** [jhomlala/betterplayer#1270]
Failed to handle method call
E/MethodChannel#better_player_channel(29209): java.lang.NullPointerException: MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior.
E/MethodChannel#better_player_channel(29209):   at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:174)
E/MethodChannel#better_player_channel(29209):   at com.google.android.exoplayer2.source.ProgressiveMediaSource$Factory.setDrmSessionManagerProvider(ProgressiveMediaSource.java:190)
E/MethodChannel#better_player_channel(29209):   at com.jhomlala.better_player.BetterPlayer.buildMediaSource(BetterPlayer.kt:430)
E/MethodChannel#better_player_channel(29209):   at com.jhomlala.better_player.BetterPlayer.setDataSource(BetterPlayer.kt:196)
E/MethodChannel#better_player_channel(29209):   at com.jhomlala.better_player.BetterPlayerPlugin.setDataSource(BetterPlayerPlugin.kt:277)
E/MethodChannel#better_player_channel(29209):   at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:151)
E/MethodChannel#better_player_channel(29209):   at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:138)
E/MethodChannel#better_player_channel(29209):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)   
E/MethodChannel#better_player_channel(29209):   at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#better_player_channel(29209):   at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#better_player_channel(29209):   at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)      
E/MethodChannel#better_player_channel(29209):   at android.os.Handler.handleCallback(Handler.java:966)
E/MethodChannel#better_player_channel(29209):   at android.os.Handler.dispatchMessage(Handler.java:110)
E/MethodChannel#better_player_channel(29209):   at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#better_player_channel(29209):   at android.os.Looper.loop(Looper.java:293)
E/MethodChannel#better_player_channel(29209):   at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
E/MethodChannel#better_player_channel(29209):   at android.app.ActivityThread.main(ActivityThread.java:9923)
E/MethodChannel#better_player_channel(29209):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#better_player_channel(29209):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
E/MethodChannel#better_player_channel(29209):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
E/flutter (29209): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, MediaSource.Factory#setDrmSessionMan
agerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retai
n the old behavior., null, java.lang.NullPointerException: MediaSource.Factory#setDrmSessionManagerProvider no longer handles null by instantiating a new DefaultDrmSessionManagerProvider. Explicitly construct and pass an instance in order to retain the old behavior.
E/flutter (29209):      at com.google.android.exoplayer2.util.Assertions.checkNotNull(Assertions.java:174)
E/flutter (29209):      at com.google.android.exoplayer2.source.ProgressiveMediaSource$Factory.setDrmSessionManagerProvider(ProgressiveMediaSource.java:190)
E/flutter (29209):      at com.jhomlala.better_player.BetterPlayer.buildMediaSource(BetterPlayer.kt:430)
E/flutter (29209):      at com.jhomlala.better_player.BetterPlayer.setDataSource(BetterPlayer.kt:196)
E/flutter (29209):      at com.jhomlala.better_player.BetterPlayerPlugin.setDataSource(BetterPlayerPlugin.kt:277)
E/flutter (29209):      at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:151)
E/flutter (29209):      at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:138)
E/flutter (29209):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (29209):      at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (29209):      at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (29209):      at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (29209):      at android.os.Handler.handleCallback(Handler.java:966)
E/flutter (29209):      at android.os.Handler.dispatchMessage(Handler.java:110)
E/flutter (29209):      at android.os.Looper.loopOnce(Looper.java:205)
E/flutter (29209):      at android.os.Looper.loop(Looper.java:293)
E/flutter (29209):      at android.app.ActivityThread.loopProcess(ActivityThread.java:9934)
E/flutter (29209):      at android.app.ActivityThread.main(ActivityThread.java:9923)
E/flutter (29209):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (29209):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
E/flutter (29209):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
E/flutter (29209): )
E/flutter (29209): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
E/flutter (29209): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
E/flutter (29209): <asynchronous suspension>
E/flutter (29209): #2      MethodChannelVideoPlayer.setDataSource (package:better_player/src/video_player/method_channel_video_player.dart:118:5)       
E/flutter (29209): <asynchronous suspension>
E/flutter (29209): #3      VideoPlayerController._setDataSource (package:better_player/src/video_player/video_player.dart:408:5)
E/flutter (29209): <asynchronous suspension>
E/flutter (29209): #4      BetterPlayerController._setupDataSource (package:better_player/src/core/better_player_controller.dart:444:9)
E/flutter (29209): <asynchronous suspension>
E/flutter (29209): #5      BetterPlayerController.setupDataSource (package:better_player/src/core/better_player_controller.dart:274:5)
E/flutter (29209): <asynchronous suspension>

请问这是怎么回事，demo好像没这个问题，咱们添加的时候要添加那些东西

**Comment by jhomlala** [comment]
Fixed in 0.1.0.
