### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rinsarmu** [jhomlala/betterplayer#1329]
getting the following error for flutter-tizen. 
The better player configuration is working fine on normal flutter project. but when I reuse the same code base for flutter-tizen I got the following errors.

[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel better_player_channel)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel better_player_channel)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannelVideoPlayer.create (package:better_player/src/video_player/method_channel_video_player.dart:37:37)
<asynchronous suspension>
#2      VideoPlayerController._create (package:better_player/src/video_player/video_player.dart:202:18)
<asynchronous suspension>
[I] flutter: AsyncSnapshot<BetterPlayerController?>(ConnectionState.waiting, null, null, null)
[E] [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method setAudioTrack on channel better_player_channel)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)

better_player: ^0.0.84

**Comment by yuanliangYL** [comment]
same issue
