### ISSUE TITLE
 One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by PhantomQuantum** [jhomlala/betterplayer#1363]
[  +15 ms] D/MediaCodec( 7938): [mId: 0] video-debug onReleaseOutputBuffer index 0 pts: 1000000080000 ptsdiff: 1000000080000 timediff: 2134290 render: 1
[ +203 ms] W/EpFrameworkFactory( 7938): activated: false jar exist: false
[  +23 ms] D/AndroidRuntime( 7938): Shutting down VM
[  +10 ms] E/AndroidRuntime( 7938): FATAL EXCEPTION: main
[        ] E/AndroidRuntime( 7938): Process: com.xxx.xxxx, PID: 7938
[        ] E/AndroidRuntime( 7938): java.lang.SecurityException: com.xxx.xxxx: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
[        ] E/AndroidRuntime( 7938): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
[        ] E/AndroidRuntime( 7938): 	at android.os.Parcel.createException(Parcel.java:3041)
[        ] E/AndroidRuntime( 7938): 	at android.os.Parcel.readException(Parcel.java:3024)
[        ] E/AndroidRuntime( 7938): 	at android.os.Parcel.readException(Parcel.java:2966)
[        ] E/AndroidRuntime( 7938): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6203)
[        ] E/AndroidRuntime( 7938): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
[        ] E/AndroidRuntime( 7938): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
[        ] E/AndroidRuntime( 7938): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
[        ] E/AndroidRuntime( 7938): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
[        ] E/AndroidRuntime( 7938): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.startOrUpdateNotification(PlayerNotificationManager.java:1165)
[        ] E/AndroidRuntime( 7938): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.handleMessage(PlayerNotificationManager.java:1415)
[        ] E/AndroidRuntime( 7938): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager.$r8$lambda$hDN6RMWHvTCSAt_reWH1_HHmp5E(Unknown Source:0)
[        ] E/AndroidRuntime( 7938): 	at com.google.android.exoplayer2.ui.PlayerNotificationManager$$ExternalSyntheticLambda0.handleMessage(Unknown Source:2)
[        ] E/AndroidRuntime( 7938): 	at android.os.Handler.dispatchMessage(Handler.java:102)
[        ] E/AndroidRuntime( 7938): 	at android.os.Looper.loopOnce(Looper.java:224)
[        ] E/AndroidRuntime( 7938): 	at android.os.Looper.loop(Looper.java:318)
[        ] E/AndroidRuntime( 7938): 	at android.app.ActivityThread.main(ActivityThread.java:8772)
[        ] E/AndroidRuntime( 7938): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 7938): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
[        ] E/AndroidRuntime( 7938): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
[        ] E/AndroidRuntime( 7938): Caused by: android.os.RemoteException: Remote stack trace:
[        ] E/AndroidRuntime( 7938): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14693)
[        ] E/AndroidRuntime( 7938): 	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12213)
[        ] E/AndroidRuntime( 7938): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3188)
[        ] E/AndroidRuntime( 7938): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2856)
[        ] E/AndroidRuntime( 7938): 	at android.os.Binder.execTransactInternal(Binder.java:1346)
[        ] E/AndroidRuntime( 7938): 
[  +16 ms] W/ScoutUtils( 7938): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
[  +94 ms] I/Process ( 7938): Process is going to kill itself!
[        ] I/Process ( 7938): java.lang.Exception
[        ] I/Process ( 7938): 	at android.os.Process.killProcess(Process.java:1356)
[        ] I/Process ( 7938): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:174)
[        ] I/Process ( 7938): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
[        ] I/Process ( 7938): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
[        ] I/Process ( 7938): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
[        ] I/Process ( 7938): Sending signal. PID: 7938 SIG: 9
[  +72 ms] Service protocol connection closed.
[        ] Lost connection to device.

**Comment by jhomlala** [comment]
Hello!

Thanks for reporting this. 

This `SecurityException` (`One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified`) occurs on Android 14 (API level 34) and higher when using older versions of ExoPlayer/Media3 (`PlayerNotificationManager`), which registered broadcast receivers without explicit export flags.

This has been resolved in newer releases of `androidx.media3`. Please update your project dependencies to use the latest version of `better_player` (or bump the Media3 dependency version in your Android configuration / pubspec if applicable).

We are closing this issue as it is resolved in updated Media3 releases. If you still encounter this exact crash on the latest version, please open a new issue with a reproduction case.
