### ISSUE TITLE
OutOfMemory Exception reproducing a big video

### ISSUE THREAD

**Issue by dvirgiln** [jhomlala/betterplayer#195]
I am using the betterplayer version 0.0.43 in a Nexus 6 emulator

The code to create the player is: `BetterPlayer.network(this._url)`

The video is 129 MB:
https://firebasestorage.googleapis.com/v0/b/fitwin-70e1e.appspot.com/o/trainers%2FLbN89dtaAuazzPTjxEcnlKBFREp2%2Fplans_draft%2Fvideos%2F586041270656?alt=media&token=4fa0e1e1-a134-4897-9e41-d2ae1b0074de

I start seeing errors in the logs:
```
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): The stack is not large enough for a start_depth of 0.
E/StudioTransport(18941): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(18941): Background young concurrent copying GC freed 31247(1055KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 200MB/200MB, paused 4.577ms total 4.266s
I/com.fitwin(18941): Background concurrent copying GC freed 11688(426KB) AllocSpace objects, 0(0B) LOS objects, 2% free, 201MB/207MB, paused 923us total 1.577s
```

And then:
```
I/chatty  (14820): uid=10135(com.fitwin) HeapTaskDaemon identical 1 line
I/com.fitwin(14820): Clamp target GC heap from 517MB to 512MB
E/ExoPlayerImplInternal(14820): Playback error
E/ExoPlayerImplInternal(14820):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(14820):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal(14820):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(14820):       at android.os.Looper.loop(Looper.java:214)
E/ExoPlayerImplInternal(14820):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(14820):   Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
E/ExoPlayerImplInternal(14820):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:444)
E/ExoPlayerImplInternal(14820):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(14820):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(14820):       at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(14820):   Caused by: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
I/com.fitwin(14820): Clamp target GC heap from 517MB to 512MB
```

The problem happened when I clicked in the fullscreen.

Steps to reproduce:
1. Play the video without full screen. Then I can see in the profiler how the memory goes up. The video is reproduced finely.
2. Click in the full screen button. What I see is that the video is reloaded again (as I can see the white bar reloading from the beginning. 
3. I can see in the memory profiler that the memory goes up and up
4. I can see that the video has this round loading icon all the time in the full screen mode.

**Comment by jhomlala** [comment]
@dvirgiln Please add android:largeHeap="true" in your AndroidManifest.xml and try again.

**Comment by jhomlala** [comment]
Closed due to no activity. Feel free to anwser in this issue and I'll reopen it.

**Comment by dvird** [comment]
@dvirgiln you solved it?
