### ISSUE TITLE
[BUG] Error on full screen 

### ISSUE THREAD

**Issue by dvirgiln** [jhomlala/betterplayer#207]
**Describe the bug**
Using the latest version 0.0.43 when clicking on the full screen button of a video that is being played:

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
A BetterPlayerController was used after being disposed.

Once you have called dispose() on a BetterPlayerController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
#3      BetterPlayerController.toggleFullScreen (package:better_player/src/core/better_player_controller.dart:333:5)
#4      _BetterPlayerMaterialControlsState._onExpandCollapse.<anonymous closure> (package:better_player/src/controls/better_player_material_controls.dart:539:31)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#24a0e
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(802.5, 367.6)
  finalLocalPosition: Offset(32.7, 22.9)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
A BetterPlayerController was used after being disposed.

Once you have called dispose() on a BetterPlayerController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
#3      BetterPlayerController.toggleFullScreen (package:better_player/src/core/better_player_controller.dart:333:5)
#4      _BetterPlayerMaterialControlsState._onExpandCollapse.<anonymous closure> (package:better_player/src/controls/better_player_material_controls.dart:539:31)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#24a0e
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(794.9, 361.1)
  finalLocalPosition: Offset(25.1, 16.4)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
**To Reproduce**

**Comment by jhomlala** [comment]
@dvirgiln Can you give me steps to reproduce (current one seems to be not filled)?  Also please upgrade to latest version 0.0.44 first.

**Comment by dvirgiln** [comment]
This is my code. Simple code:

```
import 'dart:io';

import 'package:better_player/better_player.dart';
import 'package:fitwin/i18n/fitwin_localizations.dart';
import 'package:flutter/material.dart';

/*
  Waiting for the http headers to be included as part of the video player network call:
  https://github.com/flutter/plugins/pull/2121
 */
class VideoWidget extends StatefulWidget {
  File file;
  String url;

  VideoWidget({this.file, this.url});

  @override
  _VideoWidgetState createState() => _VideoWidgetState(file, url);
}

class _VideoWidgetState extends State<VideoWidget> {
  File _file;
  String _url;

  _VideoWidgetState(this._file, this._url) {}

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    FitwinLocalizations i18n = FitwinLocalizations.of(context);

    return Theme(
        // Create a unique theme with "ThemeData"
        data: ThemeData.light().copyWith(platform: TargetPlatform.android ?? Theme.of(context).platform),
        child: this._file != null ? BetterPlayer.file(_file.path) : BetterPlayer.network(this._url));
  }
}
```
It seems that now that error disspears. 

I do not know the plugin slows down a lot my app. I am running now from an emulator, and my MAC just collapsing. I am reproducing from network a very small video uploaded from my camera. I start seeing this continuous logs:

```
port(19310): JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
I/chatty  (19310): uid=10133(com.fitwin) AudioTrack identical 3 lines
E/StudioTransport(19310): JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
I/com.fitwin(19310): Background young concurrent copying GC freed 747(466KB) AllocSpace objects, 0(0B) LOS objects, 7% free, 7136KB/7674KB, paused 2.552ms total 430.232ms
D/MediaCodec(19310): [OMX.google.h264.decoder] setting dataspace on output surface to #101
W/Gralloc3(19310): allocator 3.x is not supported
D/eglCodecCommon(19310): allocate: Ask for block of size 0x2f8000
D/eglCodecCommon(19310): allocate: ioctl allocate returned offset 0x3fea25000 size 0x2f9000
D/SoftwareRenderer(19310): setting dataspace on output surface to #101
W/com.fitwin(19310): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
I/com.fitwin(19310): Background concurrent copying GC freed 40196(1991KB) AllocSpace objects, 3(124KB) LOS objects, 39% free, 9499KB/15MB, paused 1.045ms total 1.211s
W/com.fitwin(19310): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, linking, allowed)
E/StudioTransport(19310): JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
I/chatty  (19310): uid=10133(com.fitwin) 1.raster identical 3 lines
E/StudioTransport(19310): JVMTI error: 15(JVMTI_ERROR_THREAD_NOT_ALIVE) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): Background young concurrent copying GC freed 26433(946KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 16MB/16MB, paused 766us total 3.348s
I/com.fitwin(19310): Background concurrent copying GC freed 4762(156KB) AllocSpace objects, 0(0B) LOS objects, 26% free, 16MB/22MB, paused 6.137ms total 947.232ms
D/AudioTrack(19310): getTimestamp_l(28): device stall time corrected using current time 45682400395070
W/AudioTrack(19310): getTimestamp_l(28): retrograde timestamp time corrected, 45682422152070 < 45682429046070
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 
I/com.fitwin(19310): The stack is not large enough for a start_depth of 0.
E/StudioTransport(19310): JVMTI error: 103(JVMTI_ERROR_ILLEGAL_ARGUMENT) 

```
I really like the look/like of the plugin, as it improves chewie (looks more pro). But it is not performing well.

**Comment by dvirgiln** [comment]
To see how the video slowed down is just to play a video. The video that is trying to play is this:

https://firebasestorage.googleapis.com/v0/b/fitwin-70e1e.appspot.com/o/trainers%2FLbN89dtaAuazzPTjxEcnlKBFREp2%2Fplans_draft%2Fvideos%2Ftdo2yWUa5RyE?alt=media&token=fc47362f-2b37-4beb-8838-b7d13d45d565

**Comment by dvirgiln** [comment]
I tried the same version on my Redmi note:

```
I/ExoPlayerImpl(25192): Init dc5da84 [ExoPlayerLib/2.12.1] [willow, Redmi Note 8T, Xiaomi, 29]
D/AudioManager(25192): getStreamVolume isRestricted mode = 0
D/SurfaceUtils(25192): connecting to surface 0x714eb0d010, reason connectToSurface
I/MediaCodec(25192): [OMX.qcom.video.decoder.avc] setting surface generation to 25796616
D/SurfaceUtils(25192): disconnecting from surface 0x714eb0d010, reason connectToSurface(reconnect)
D/SurfaceUtils(25192): connecting to surface 0x714eb0d010, reason connectToSurface(reconnect)
I/ExtendedACodec(25192): setupVideoDecoder()
E/ExtendedACodec(25192): [OMX.qcom.video.decoder.avc] configureCodec returning error -12
E/ACodec  (25192): signalError(omxError 0x80001001, internalError -12)
E/ACodec  (25192): [OMX.qcom.video.decoder.avc] configureCodec returning error -12
E/ACodec  (25192): signalError(omxError 0x80001001, internalError -12)
E/MediaCodec(25192): Codec reported err 0xfffffff4, actionCode 0, while in state 3
D/SurfaceUtils(25192): disconnecting from surface 0x714eb0d010, reason disconnectFromSurface
E/MediaCodec(25192): Codec reported err 0xfffffff4, actionCode 0, while in state 0
E/MediaCodec(25192): configure failed with err 0xfffffff4, resetting...
I/OMXClient(25192): IOmx service obtained
W/MediaCodecRenderer(25192): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(25192):   android.media.MediaCodec$CodecException: Error 0xfffffff4
W/MediaCodecRenderer(25192):       at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer(25192):       at android.media.MediaCodec.configure(MediaCodec.java:2023)
W/MediaCodecRenderer(25192):       at android.media.MediaCodec.configure(MediaCodec.java:1951)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:43)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:580)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1143)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
W/MediaCodecRenderer(25192):       at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer(25192):       at android.os.Looper.loop(Looper.java:225)
W/MediaCodecRenderer(25192):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(25192): Playback error
E/ExoPlayerImplInternal(25192):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 30.075188], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal(25192):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(25192):       at android.os.Looper.loop(Looper.java:225)
E/ExoPlayerImplInternal(25192):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(25192):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 30.075188], [-1, -1])
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1047)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal(25192):       ... 3 more
E/ExoPlayerImplInternal(25192):   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/ExoPlayerImplInternal(25192):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(25192):       at android.media.MediaCodec.configure(MediaCodec.java:2023)
E/ExoPlayerImplInternal(25192):       at android.media.MediaCodec.configure(MediaCodec.java:1951)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:43)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:580)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1143)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
E/ExoPlayerImplInternal(25192):       ... 10 more
I/flutter (25192): [firebase_storage/object-not-found] No object exists at the desired reference.
E/flutter (25192): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 30.075188], [-1, -1]), format_supported=YES, null, null)
E/flutter (25192): 
I/flutter (25192): Getting image from trainers/LbN89dtaAuazzPTjxEcnlKBFREp2/plans_draft/images/tdo2yWUa5RyE_thumbnail.png
I/OMXClient(25192): IOmx service obtained
D/SurfaceUtils(25192): connecting to surface 0x7163db4010, reason connectToSurface
I/MediaCodec(25192): [OMX.qcom.video.decoder.avc] setting surface generation to 25796617
D/SurfaceUtils(25192): disconnecting from surface 0x7163db4010, reason connectToSurface(reconnect)
D/SurfaceUtils(25192): connecting to surface 0x7163db4010, reason connectToSurface(reconnect)
E/StorageException(25192): StorageException has occurred.
E/StorageException(25192): Object does not exist at location.
E/StorageException(25192):  Code: -13010 HttpResult: 404
E/StorageException(25192): {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException(25192): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException(25192): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:434)
E/StorageException(25192): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:451)
E/StorageException(25192): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:442)
E/StorageException(25192): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException(25192): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:286)
E/StorageException(25192): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:70)
E/StorageException(25192): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:62)
E/StorageException(25192): 	at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:76)
E/StorageException(25192): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException(25192): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException(25192): 	at java.lang.Thread.run(Thread.java:919)
I/flutter (25192): [firebase_storage/object-not-found] No object exists at the desired reference.
I/ExtendedACodec(25192): setupVideoDecoder()
E/ExtendedACodec(25192): [OMX.qcom.video.decoder.avc] configureCodec returning error -12
E/ACodec  (25192): signalError(omxError 0x80001001, internalError -12)
E/ACodec  (25192): [OMX.qcom.video.decoder.avc] configureCodec returning error -12
E/ACodec  (25192): signalError(omxError 0x80001001, internalError -12)
E/MediaCodec(25192): Codec reported err 0xfffffff4, actionCode 0, while in state 3
D/SurfaceUtils(25192): disconnecting from surface 0x7163db4010, reason disconnectFromSurface
E/MediaCodec(25192): Codec reported err 0xfffffff4, actionCode 0, while in state 0
E/MediaCodec(25192): configure failed with err 0xfffffff4, resetting...
I/OMXClient(25192): IOmx service obtained
W/MediaCodecRenderer(25192): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer(25192):   android.media.MediaCodec$CodecException: Error 0xfffffff4
W/MediaCodecRenderer(25192):       at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer(25192):       at android.media.MediaCodec.configure(MediaCodec.java:2023)
W/MediaCodecRenderer(25192):       at android.media.MediaCodec.configure(MediaCodec.java:1951)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:43)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:580)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1143)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
W/MediaCodecRenderer(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
W/MediaCodecRenderer(25192):       at android.os.Handler.dispatchMessage(Handler.java:103)
W/MediaCodecRenderer(25192):       at android.os.Looper.loop(Looper.java:225)
W/MediaCodecRenderer(25192):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(25192): Playback error
E/ExoPlayerImplInternal(25192):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 30.075188], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:542)
E/ExoPlayerImplInternal(25192):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal(25192):       at android.os.Looper.loop(Looper.java:225)
E/ExoPlayerImplInternal(25192):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(25192):   Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 30.075188], [-1, -1])
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1047)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:604)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1470)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:640)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readToFlagsOnlyBuffer(MediaCodecRenderer.java:994)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:844)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:892)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:467)
E/ExoPlayerImplInternal(25192):       ... 3 more
E/ExoPlayerImplInternal(25192):   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
E/ExoPlayerImplInternal(25192):       at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(25192):       at android.media.MediaCodec.configure(MediaCodec.java:2023)
E/ExoPlayerImplInternal(25192):       at android.media.MediaCodec.configure(MediaCodec.java:1951)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.configure(SynchronousMediaCodecAdapter.java:43)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:580)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1143)
E/ExoPlayerImplInternal(25192):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1040)
E/ExoPlayerImplInternal(25192):       ... 10 more
E/flutter (25192): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, null, -1, null, [1920, 1080, 30.075188], [-1, -1]), format_supported=YES, null, null)
E/flutter (25192): 
D/AudioTrack(25192): stop(588): called with 567296 frames delivered

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3906:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3920:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:3962:12)
#3      InheritedWorkoutPlanEditState.of (package:fitwin/screen/trainer/workout/edit/shared_state.dart:42:20)
#4      WorkoutPlanEditBodyWidgetState.dispose (package:fitwin/screen/trainer/workout/edit/body.dart:49:39)
...

This error happened after a few times clicking the full screen for the same video. For some reason it just cannot handle it.

```

**Comment by jhomlala** [comment]
@dvirgiln Seems like exoplayer issue: https://github.com/google/ExoPlayer/issues/6168

**Comment by jhomlala** [comment]
Some devices can instantiate only one instance of exo player. So if you open more than 1 player in app, this may lead to this error. Try to use one BetterPlayerController and BetterPlayer at time.

**Comment by jhomlala** [comment]
Closed due to no activity. Feel free to anwser in this issue and I'll reopen it.
