### ISSUE TITLE
[BUG] Once you have called dispose() on a VideoPlayerController, it can no longer be used

### ISSUE THREAD

**Issue by HiroyukTamura** [jhomlala/betterplayer#244]
**Describe the bug**

An exception is thrown when invoked `BetterPlayerController.setupDataSource` .

```
Once you have called dispose() on a VideoPlayerController, it can no longer be used.
E/flutter (20894): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
E/flutter (20894): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
E/flutter (20894): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:217:12)
E/flutter (20894): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:292:5)
E/flutter (20894): #4      VideoPlayerController.setLooping (package:better_player/src/video_player/video_player.dart:436:5)
E/flutter (20894): #5      BetterPlayerController._initialize (package:better_player/src/core/better_player_controller.dart:317:33)
E/flutter (20894): #6      BetterPlayerController._setupDataSource (package:better_player/src/core/better_player_controller.dart:306:11)
E/flutter (20894): <asynchronous suspension>
E/flutter (20894): #7      BetterPlayerController.setupDataSource (package:better_player/src/core/better_player_controller.dart:210:11)
E/flutter (20894): <asynchronous suspension>
E/flutter (20894): #8      new BetterPlayerController (package:better_player/src/core/better_player_controller.dart:149:7)
E/flutter (20894): #9      _PlayerViewState._createController (package:shirasu/screen_detail/screen_detail/video_header/player_view.dart:213:12)
E/flutter (20894): #10     _PlayerViewState.initState (package:shirasu/screen_detail/screen_detail/video_header/player_view.dart:41:19)
E/flutter (20894): #11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (20894): #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (20894): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (20894): #14     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
E/flutter (20894): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (20894): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (20894): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (20894): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (20894): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (20894): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (20894): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (20894): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (20894): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (20894): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (20894): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (20894): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (20894): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (20894): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (20894): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (20894): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (20894): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (20894): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (20894): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (20894): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (20894): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (20894): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (20894): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
E/flutter (20894): #38     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:140:18)
E/flutter (20894): #39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2683:19)
E/flutter (20894): #40     _LayoutBuilderElement._layout (package:flutter/src/widgets
```

**To Reproduce**
BetterPlayerController.setupDataSource and rebuild immediately.
then the exception is thrown because of lack of check if `videoPlayerController` is disposed at `BetterPlayerController._initialize`

**Flutter doctor**
```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale ja-JP)
    • Flutter version 1.22.5 at /Users/hiroyukitamura/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/hiroyukitamura/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/hiroyukitamura/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Users/hiroyukitamura/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/201.7042882/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Users/hiroyukitamura/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7033425/Android Studio 4.2 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Connected device (2 available)
    • SM A205GN (mobile)       • R58M60CA79W                              • android-arm64 • Android 10 (API 29)
    • HiroyukiのiPhone (mobile) • b169007869e15a81740b891bf15b6968ae2b750d • ios           • iOS 14.3
```

**Better Player version**
- Version: 0.0.45

**Comment by jhomlala** [comment]
Can you share your code? Probably you are disposing BetterPlayer which triggers BetterPlayerController dispose. To handle scenarios like this, you can add key to your widget, so it will prevent unnecessary rebuilds.

**Comment by HiroyukTamura** [comment]
ahh, I have incorrect code in my project. It causes verbose rebuildings.
thanks for your fast reply.

but is it intended that there is no check if is videoPlayerController disposed?
isn't it a little dangerous?

**Comment by jhomlala** [comment]
It's not dangerous, because it only happens during development. On normal app work, it shouldn't happen. When I've been hot reloading example app, I didn't encounter this issue. Maybe in your widget tree, Better Player was rebuilt each time.
