### ISSUE TITLE
Player not working 

### ISSUE THREAD

**Issue by armanhadifatah** [jhomlala/betterplayer#26]
This is my code for the widget :
```

import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:better_player/better_player.dart';

class BetterPlayerWidget extends StatefulWidget {
  final String videoUrl;
  Function videoPlayerValue;
  final timePassed;

  BetterPlayerWidget(this.videoUrl, {this.videoPlayerValue, this.timePassed});

  @override
  State<StatefulWidget> createState() {
    return BetterPlayerWidgetState();
  }
}

class BetterPlayerWidgetState extends State<BetterPlayerWidget> {
  BetterPlayerController _betterPlayerController;

  final double playerWidth = 640;
  final double playerHeight = 360;


  @override
  void initState() {
    super.initState();
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.NETWORK,
         "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4");
    _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(),
        betterPlayerDataSource: betterPlayerDataSource);
  }

  Widget build(BuildContext context) {
        Size size = MediaQuery.of(context).size;
    double width = size.width;
    return Container(
        height: 300,
        width: width,
           child: BetterPlayer(
        controller: _betterPlayerController,
        ));
  }

  @override
  void dispose() {
    super.dispose();
  }
}

```

This is the error : 

```
Init e03093e [ExoPlayerLib/2.11.1] [lavender, Redmi Note 7, Xiaomi, 28]
E/MethodChannel#flutter.io/videoPlayer( 7379): Failed to handle method call
E/MethodChannel#flutter.io/videoPlayer( 7379): java.lang.NullPointerException: uriString
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at android.net.Uri$StringUri.<init>(Uri.java:490)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at android.net.Uri$StringUri.<init>(Uri.java:480)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at android.net.Uri.parse(Uri.java:452)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at io.flutter.plugins.videoplayer.VideoPlayer.<init>(VideoPlayer.java:73)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onMethodCall(VideoPlayerPlugin.java:133)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter.io/videoPlayer( 7379): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter ( 7379): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, uriString, null)
E/flutter ( 7379): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter ( 7379): #1      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:156
E/flutter ( 7379): <asynchronous suspension>
E/flutter ( 7379): #2      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:329
E/flutter ( 7379): #3      MethodChannel.invokeMapMethod 
package:flutter/…/services/platform_channel.dart:356
E/flutter ( 7379): #4      MethodChannelVideoPlayer.create 
package:better_player/…/video_player/method_channel_video_player.dart:33
E/flutter ( 7379): #5      VideoPlayerController._create 
package:better_player/…/video_player/video_player.dart:188
E/flutter ( 7379): #6      new VideoPlayerController 
package:better_player/…/video_player/video_player.dart:164
E/flutter ( 7379): #7      BetterPlayerController._setup 
package:better_player/…/core/better_player_controller.dart:101
E/flutter ( 7379): #8      new BetterPlayerController 
package:better_player/…/core/better_player_controller.dart:81
E/flutter ( 7379): #9      BetterPlayerWidgetState.initState 
package:wane/…/video_player/betterPlayer.dart:31
E/flutter ( 7379): #10     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4649
E/flutter ( 7379): #11     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4485
E/flutter ( 7379): #12     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3455
E/flutter ( 7379): #13     Element.updateChild 
package:flutter/…/widgets/framework.dart:3223
E/flutter ( 7379): #14     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5839
E/flutter ( 7379): #15     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3455
E/flutter ( 7379): #16     Element.updateChild 
package:flutter/…/widgets/framework.dart:3223
E/flutter ( 7379): #17     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4536
E/flutter ( 7379): #18     Element.rebuild 
package:flutter/…/widgets/framework.dart:4227
E/flutter ( 7379): #19     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4490
E/flutter ( 7379): #20     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4485
E/flutter ( 7379): #21     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3455
E/flutter ( 7379): #22     MultiChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5956
E/flutter ( 7379): #23     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3455
E/flutter ( 7379): #24     Element.updateChild 
package:flutter/…/widgets/framework.dart:3223
E/flutter ( 7379): #25     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4536
E/flutter ( 7379): #26     Element.rebuild 
package:flutter/…/widgets/framework.dart:4227
E/flutter ( 7379): #27     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4490
E/flutter ( 7379): #28     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4485
E/flutter ( 7379): #29     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3455
E/flutter ( 7379): #30     Element.updateChild 
package:flutter/…/widgets/framework.dart:3223
E/flutter ( 7379): #31     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4536
E/flutter ( 7379): #32     Element.rebuild 
package:flutter/…/widgets/framework.dart:4227
E/flutter ( 7379): #33     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4490
E/flutter ( 7379): #34     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4485
E/flutter ( 7379): #35     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3455
E/flutter ( 7379): #36     Element.updateChild 
package:flutter/…/widgets/framework.dart:3223
E/flutter ( 7379): #37     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4536
E/flutter ( 7379): #38     Element.rebuild 
package:flutter/…/widgets/framework.dart:4227
E/flutter ( 7379): #39     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4490
E/flutter ( 7379): #40     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4485
E/flutter ( 7379): #41     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3455
E/flutter ( 7379): #42     MultiChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5956
E/flutter ( 7379): #43     Element.inflateWidget 
```

**Comment by jhomlala** [comment]
Given example works on my device. Can you check it on another device?

**Comment by leszekkrol** [comment]
Any update?

**Comment by jhomlala** [comment]
No update from issue author. Closing.
