### ISSUE TITLE
[BUG] Elements being dispose after rebuild

### ISSUE THREAD

**Issue by maares** [jhomlala/betterplayer#269]
Hi, I'm trying your plugin with the intent of migrating from Chewie. Most likely I'm mistaken doing something I should not be doing.  I know the packages contains several ways to include list, BetterPlayerListVideoPlayer, or reusable list, although I have several tabs, with several post that might have or not Audio / Video, loading different customControls depending on the size, page etc. They can be played from the front page, expanded, full screen, collapsed or within the post route. Hope you can clarify, were should I be aiming in order to achieve the migration.

Doing same basics, each time I transitioned from a tab to another all videos got disposed i.e, no longer visible (assuming). Set the autoDispose to false, but its not having any effect. Tried to see issues raised and encountered a few, but with no luck #21, #55, #141. From your readme you mention the following: 

> Your event listener will ne auto-disposed on dispose time :)

Could you explain further the behaviour implemented?

**Describe the bug**
BetterPlayerControllers are being disposed when widget tree is refreshed.

**To Reproduce**
1. Generate a List of videos

![Simple list beeing dispose](https://user-images.githubusercontent.com/37770669/106988520-46fe4880-6770-11eb-9471-98dbbc1eb669.gif)

**Expected behavior**
Not to dispose controller when widget refresh

What I'm trying to migrate. 

![Aiming to achive](https://user-images.githubusercontent.com/37770669/106988528-4b2a6600-6770-11eb-81ff-58cbe0e6d95a.gif)

**Flutter doctor**
[Saturn:~/code/flutter/wordpress] mares% flutter doctor --verbose
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.2 20D64 darwin-x64, locale en-ES)
    • Flutter version 1.25.0-8.3.pre at /Users/mares/Library/flutter
    • Framework revision 5d36f2e7f5 (3 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mares/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.53.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • iPhone SE (2nd generation) (mobile) • 5C504E96-FD72-4845-9C28-C7C671683803 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

**Better Player version**
- better_player: ^0.0.49

**Package to manage better player controller **
- get: ^3.23.1

**Smartphone (please complete the following information):**
 - Device: Iphone SE Second Gen.

**Additional context**

Console error (same for every element in the list)

> [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: A BetterPlayerController was used after being disposed.
> Once you have called dispose() on a BetterPlayerController, it can no longer be used.
> #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure>
> package:flutter/…/foundation/change_notifier.dart:117
> #1      ChangeNotifier._debugAssertNotDisposed
> package:flutter/…/foundation/change_notifier.dart:123
> #2      ChangeNotifier.addListener
> package:flutter/…/foundation/change_notifier.dart:176
> #3      BetterPlayerState._setup
> package:better_player/…/core/better_player.dart:98
> #4      BetterPlayerState.initState.<anonymous closure>
> package:better_player/…/core/better_player.dart:81
> #5      new Future.delayed.<anonymous closure> (dart:async/future.dart:329:39)
> #6      _rootRun (dart:async/zone.dart:1178:47)
> #7      _CustomZone.run (dart:async/zone.dart:1090:19)
> #8      _CustomZone.runGuarded (dart:async/zone.dart:994:7)

import 'package:flutter/material.dart';
import 'package:wordpress/modules/better_player/ui/better_player_expanded_widget.dart';

1. Generate a list
```
class TestView extends StatelessWidget {
  final List<String> urls = [
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        itemCount: urls.length,
        itemBuilder: (context, i) {
          return BetterPlayerExpandedWidget(url: urls[i]);
        },
      ),
    );
  }
}
```

2. Calling BetterPlayerExpandedWidget

```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:wordpress/modules/better_player/better_player_ctrl.dart';

class BetterPlayerExpandedWidget extends StatelessWidget {
  BetterPlayerExpandedWidget({
    Key key,
    @required String url,
  })  : _url = url,
        super(key: key);

  final String _url;

  @override
  Widget build(BuildContext context) {
    BetterPlayerCtrl betterPlayerCtrl = Get.put(
      BetterPlayerCtrl(url: _url),
      tag: _url,
    );

    return Obx(
      () {
        return !betterPlayerCtrl.isVideoInitialize.value
            ? Center(child: CircularProgressIndicator())
            : AspectRatio(
                aspectRatio: 16 / 9,
                child: Container(
                  color: Colors.black,
                  margin: EdgeInsets.symmetric(horizontal: 0.0, vertical: 0),
                  padding: EdgeInsets.symmetric(horizontal: 0.0, vertical: 0),
                  child: BetterPlayer(
                    controller: betterPlayerCtrl.betterPlayerController,
                  ),
                ),
              );
      },
    );
  }
}
```

3. BetterPlayer Setup

```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:wordpress/modules/init/common_functions.dart';

class BetterPlayerCtrl extends GetxController
    with SingleGetTickerProviderMixin {
  BetterPlayerCtrl({this.url});
  final String url;
  final CommonFunctions commonFunctions = Get.find<CommonFunctions>();

  AnimationController playPauseIconAnimationController;

  BetterPlayerController betterPlayerController;
  BetterPlayerDataSource betterPlayerDataSource;

  final RxString positionRender = ''.obs;
  final RxDouble videoPosition = 0.0.obs;
  final RxBool justEnteredFullScreen = false.obs;
  final RxBool isVideoFinishPLaying = false.obs;
  final RxBool isVideoInitialize = false.obs;
  final RxBool isVideoFullScreen = false.obs;
  final RxBool isVideoPlaying = false.obs;
  final RxBool isVideoControlsHidden = false.obs;
  // final RxDouble videoProgress =

  BetterPlayerConfiguration betterPlayerConfiguration =
      BetterPlayerConfiguration(
    aspectRatio: 16 / 9,
    allowedScreenSleep: true,
    autoDetectFullscreenDeviceOrientation: true, //review
    autoDispose: false,   // <-------- AIMING TO CONTROL WHEN TO DISPOSE
    autoPlay: false,
    controlsConfiguration: BetterPlayerControlsConfiguration(
      backwardSkipTimeInMilliseconds: 1000, // review
      controlBarColor: Colors.transparent,
      controlBarHeight: 30,
      controlsHideTime: Duration(seconds: 2),
      enableFullscreen: true,
      enableMute: false,
      enableOverflowMenu: true,
      enablePip: true,

      /// customControlsBuilder: , //FIXME migrate Chewie custom Controls
      enablePlayPause: true,
      enablePlaybackSpeed: false,
      enableProgressBar: true,
      enableProgressText: true,
      enableQualities: true,
      enableRetry: true,
      enableSkips: true,
      enableSubtitles: true,
      forwardSkipTimeInMilliseconds: 15000,
      // fullscreenDisableIcon: false,
      liveTextColor: Get.context.theme.primaryColor,
      playerTheme: BetterPlayerTheme.material,
      // customControlsBuilder: ,
      progressBarHandleColor: Get.context.theme.primaryColor,
      progressBarPlayedColor: Get.context.theme.primaryColor,
      showControls: true,
      showControlsOnInitialize: false,
      progressBarBufferedColor: Get.context.theme.primaryColor.withAlpha(100),
    ),
  );

  @override
  Future<void> onInit() async {
    playPauseIconAnimationController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 400),
      reverseDuration: const Duration(milliseconds: 400),
    );
    await initVideo(url: url);
    super.onInit();
  }

  @override
  Future<void> onReady() async {
    super.onReady();
  }

  @override
  void onClose() {
    super.onClose();
  }

  Future<void> initVideo({String url}) async {
    ///VALIDATIONS
    if (url.contains('.youtube.com')) {
      final String ytUrl = await commonFunctions.extractVideoUrl(url);
      betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        ytUrl,
      );
    } else {
      betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        url,
      );
    }

    betterPlayerController = BetterPlayerController(BetterPlayerConfiguration(),
        betterPlayerDataSource: betterPlayerDataSource);

    betterPlayerController
      ..addEventsListener((event) async {
        await betterPlayerListener(event: event);
      });

    // isVideoInitialize.toggle();
  }

  Future<void> betterPlayerListener({BetterPlayerEvent event}) async {
    switch (event.betterPlayerEventType) {
      case BetterPlayerEventType.initialized:
        isVideoInitialize.value = true;
        break;
      default:
    }
    //TODO Migrate all events: isPlaying, Timer, Expanded, Collapsed video
  }
}

```

**Comment by maares** [comment]
Omg, I jut realize I was wrongly doing the setUp!

From
 ```
 betterPlayerController = BetterPlayerController(**BetterPlayerConfiguration(),**
         betterPlayerDataSource: betterPlayerDataSource);
 ```

To

```
betterPlayerController = BetterPlayerController(
      **betterPlayerConfiguration,**
      betterPlayerDataSource: betterPlayerDataSource,
    );
```

Once I corrected the setup, no more videos are being dispose. 

Very sry, seems doing this attempt of migration at 4 am here was not good idea xD

**Comment by maares** [comment]
Hi unfortunately, still having the videos disposed after full screen:

Hopefully this is a silly mistake from my part again, and someone can catch it out on the fly.

https://user-images.githubusercontent.com/37770669/107064463-d1c85d00-67db-11eb-8796-7997d8200402.mp4




**Source code**

1. List with urls
```
import 'package:flutter/material.dart';
import 'package:wordpress/modules/better_player/ui/better_player_expanded_widget.dart';

class TestView extends StatelessWidget {
  final List<String> urls = [
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: ListView.builder(
        itemCount: urls.length,
        itemBuilder: (context, i) {
          return BetterPlayerExpandedWidget(videoUrl: urls[i]);
        },
      ),
    );
  }
}

```

BetterPlayerExpandedWidget who calls  / creates it's own controller for each video:

```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:wordpress/modules/better_player/better_player_ctrl.dart';
import 'package:wordpress/widgets/general/circular_progress_indicator_widget.dart';

class BetterPlayerExpandedWidget extends StatelessWidget {
  BetterPlayerExpandedWidget({
    Key key,
    @required String videoUrl,
    String videoImageUrl,
  })  : _videoUrl = videoUrl,
        _videoImageUrl = videoImageUrl,
        super(key: key);

  final String _videoUrl;
  final String _videoImageUrl;

  @override
  Widget build(BuildContext context) {
    BetterPlayerCtrl betterPlayerCtrl = Get.put(
      BetterPlayerCtrl(
        videoUrl: _videoUrl,
        videoImageUrl: _videoImageUrl,
      ),
      tag: _videoUrl,
    );

    return Obx(
      () {
        return !betterPlayerCtrl.isVideoInitialize.value
            ? CircularProgressIndicatorWidget()
            : AspectRatio(
                aspectRatio: 16 / 9,
                child: Container(
                  color: Colors.black,
                  margin: EdgeInsets.symmetric(horizontal: 0.0, vertical: 0),
                  padding: EdgeInsets.symmetric(horizontal: 0.0, vertical: 0),
                  child: BetterPlayer(
                    controller: betterPlayerCtrl.betterPlayerController,
                  ),
                ),
              );
      },
    );
  }
}

```

BetterPlayerCrtl

```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';
import 'package:wordpress/modules/init/common_functions.dart';

class BetterPlayerCtrl extends GetxController
    with SingleGetTickerProviderMixin {
  BetterPlayerCtrl({
    @required this.videoUrl,
    this.videoImageUrl,
  });

  final String videoUrl;
  final String videoImageUrl;

  final CommonFunctions commonFunctions = Get.find<CommonFunctions>();
  final RxString positionRender = ''.obs;
  final RxDouble videoPosition = 0.0.obs;
  final RxBool justEnteredFullScreen = false.obs;
  final RxBool isVideoFinishPLaying = false.obs;
  final RxBool isVideoInitialize = false.obs;
  final RxBool isVideoFullScreen = false.obs;
  final RxBool isVideoPlaying = false.obs;
  final RxBool isVideoControlsHidden = false.obs;

  final List<DeviceOrientation> _normalOrientations = [
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
    DeviceOrientation.landscapeLeft,
    DeviceOrientation.landscapeRight
  ];
  final List<DeviceOrientation> _portraitOrientation = [
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ];
  final List<DeviceOrientation> _landscapeOrientation = [
    DeviceOrientation.landscapeLeft,
    DeviceOrientation.landscapeRight
  ];

  Orientation _orientationBeforeFullScreen;
  BetterPlayerDataSource betterPlayerDataSource;
  BetterPlayerController betterPlayerController;
  BetterPlayerConfiguration betterPlayerConfiguration;
  AnimationController playPauseIconAnimationController;

  @override
  Future<void> onInit() async {
    initVideoPlayerConfiguration();
    await initVideo(url: videoUrl);
    super.onInit();
  }

  @override
  Future<void> onReady() async {
    super.onReady();
  }

  @override
  void onClose() {
    super.onClose();
  }

  Future<void> initVideo({String url}) async {
    ///VALIDATIONS
    if (url.contains('.youtube.com')) {
      final String ytUrl = await commonFunctions.extractVideoUrl(url);
      betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        ytUrl,
      );
    } else {
      betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.network,
        url,
        
      );
    }

    betterPlayerController = BetterPlayerController(
      betterPlayerConfiguration,
      betterPlayerDataSource: betterPlayerDataSource,

    );

    betterPlayerController
      ..addEventsListener((event) async {
        await betterPlayerListener(event: event);
      });

  }

  Future<void> betterPlayerListener({BetterPlayerEvent event}) async {
    print('Event: ${event.betterPlayerEventType.toString().split('.').last}');

    switch (event.betterPlayerEventType) {
      case BetterPlayerEventType.initialized:
        isVideoInitialize.value = true;
        break;
      case BetterPlayerEventType.openFullscreen:
        _orientationBeforeFullScreen = Get.context.orientation;
        break;
      case BetterPlayerEventType.hideFullscreen:
        if (_orientationBeforeFullScreen == Orientation.portrait) {
          SystemChrome.setPreferredOrientations(_portraitOrientation);
        }
        if (_orientationBeforeFullScreen == Orientation.landscape) {
          SystemChrome.setPreferredOrientations(_landscapeOrientation);
        }
        Future.delayed(Duration(milliseconds: 500), () {
          SystemChrome.setPreferredOrientations(_normalOrientations);
        });
        break;
      default:
    }
  }

  void initVideoPlayerConfiguration() {
    betterPlayerConfiguration = BetterPlayerConfiguration(
      aspectRatio: 16 / 9,
      looping: false,
      handleLifecycle: true,
      showPlaceholderUntilPlay: true,
      autoDetectFullscreenDeviceOrientation: true, //review
      autoPlay: false,
      autoDispose: false, // <-------- AIMING TO CONTROL WHEN TO DISPOSE
      allowedScreenSleep: true,

      // placeholder: NetworkImagePlaceholderWidget(
      //   imageUrl: videoImageUrl,
      //   imageErrorPlaceHolder: 'asset_not_found',
      // ),

      // playerVisibilityChangedBehavior: asd,
      // controlsConfiguration: BetterPlayerControlsConfiguration(
      // controlBarHeight: 30,
      // controlsHideTime: Duration(seconds: 1),
      // controlBarColor: Colors.transparent,
      // showControls: true,
      // showControlsOnInitialize: false,
      // forwardSkipTimeInMilliseconds: 15000,
      // backwardSkipTimeInMilliseconds: 15000,
      // playerTheme: BetterPlayerTheme.material,
      // liveTextColor: Get.context.theme.primaryColor,
      // progressBarHandleColor: Get.context.theme.primaryColor,
      // progressBarPlayedColor: Get.context.theme.primaryColor,
      // progressBarBufferedColor: Get.context.theme.primaryColor.withAlpha(100),
      // enablePip: true,
      // enableMute: false,
      // enableRetry: true,
      // enableSkips: true,
      // enableSubtitles: true,
      // enablePlayPause: true,
      // enableQualities: true,
      // enableFullscreen: true,
      // enableProgressBar: true,
      // enableProgressText: true,
      // enableOverflowMenu: true,
      // enablePlaybackSpeed: false,
      // ),
    );
  }
}

```

[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
#0      State.context.<anonymous closure>
package:flutter/…/widgets/framework.dart:1090
#1      State.context
package:flutter/…/widgets/framework.dart:1096
#2      BetterPlayerState.onFullScreenChanged
package:better_player/…/core/better_player.dart:151
#3      ChangeNotifier.notifyListeners
package:flutter/…/foundation/change_notifier.dart:243
#4      BetterPlayerController.exitFullScreen
package:better_player/…/core/better_player_controller.dart:381
#5      BetterPlayerState._pushFullScreenWidget
package:better_player/…/core/better_player.dart:262
<asynchronous suspension>
#6      BetterPlayerState.onFullScreenChanged
package:better_player/…/core/better_player.dart:149
<asyn<…>
