### ISSUE TITLE
[BUG] Unhandled Exception when scrolling in listview with reusable video controller

### ISSUE THREAD

**Issue by mstrkn** [jhomlala/betterplayer#367]
**History check**
Hello sir, i confirm that I have checked the history without finding anything that could help me solve my issue.

**Describe the bug**
Unhandled Exception when scrolling a listview with reusable video list controller implementation. When the error appears, the first video in the list appears instead of all the others when you scroll over them and they are about to start.

**To Reproduce**
1. Scroll down listview
2. See error
```
E/flutter (11140): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: setState() called after dispose(): _BetterPlayerVideoFitWidgetState#bcc34(lifecycle state: defunct, not mounted)
E/flutter (11140): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (11140): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (11140): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (11140): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1208:9)
E/flutter (11140): #1      State.setState (package:flutter/src/widgets/framework.dart:1243:6)
E/flutter (11140): #2      _BetterPlayerVideoFitWidgetState._initialize.<anonymous closure> (package:better_player/src/core/better_player_with_controls.dart:290:9)
E/flutter (11140): #3      BetterPlayerController._postEvent (package:better_player/src/core/better_player_controller.dart:599:22)
E/flutter (11140): #4      BetterPlayerController.postEvent (package:better_player/src/core/better_player_controller.dart:592:5)
E/flutter (11140): #5      BetterPlayerController.setupDataSource (package:better_player/src/core/better_player_controller.dart:222:5)
E/flutter (11140): #6      _PostVideoContentState._setupController (package:scarface/view/templates/post_item_template.dart:307:18)
E/flutter (11140): #7      _PostVideoContentState.build.<anonymous closure> (package:scarface/view/templates/post_item_template.dart:373:17)
E/flutter (11140): #8      VisibilityDetectorLayer._fireCallback (package:visibility_detector/src/visibility_detector_layer.dart:268:24)
E/flutter (11140): #9      VisibilityDetectorLayer._processCallbacks (package:visibility_detector/src/visibility_detector_layer.dart:239:13)
E/flutter (11140): #10     _TaskEntry.run.<anonymous closure> (package:flutter/src/scheduler/binding.dart:80:34)
E/flutter (11140): #11     Timeline.timeSync (dart:developer/timeline.dart:163:22)
E/flutter (11140): #12     _TaskEntry.run (package:flutter/src/scheduler/binding.dart:77:16)
E/flutter (11140): #13     SchedulerBinding.handleEventLoopCallback (package:flutter/src/scheduler/binding.dart:460:15)
E/flutter (11140): #14     SchedulerBinding._runTasks (package:flutter/src/scheduler/binding.dart:438:9)
E/flutter (11140): #15     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (11140): #16     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (11140): #17     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (11140): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (11140): #19     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (11140): #20     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (11140): #21     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (11140): #22     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (11140): #23     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (11140): #24     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (11140): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Example code*

```
class PostVideoContent extends StatefulWidget {
  final double ratio;
  final bool isSinglePost;
  final double finalWidth;
  final double finalHeight;
  final VideoData videoData;
  final Function canBuildVideo;
  final bool muteVideoPostAtStart;
  final ReusableVideoListController videoListController;

  PostVideoContent({
    Key key,
    this.ratio,
    this.videoData,
    this.finalWidth,
    this.finalHeight,
    this.isSinglePost,
    this.canBuildVideo,
    this.videoListController,
    this.muteVideoPostAtStart,
  }) : super(key: key);

  @override
  _PostVideoContentState createState() => _PostVideoContentState();
}

class _PostVideoContentState extends State<PostVideoContent> {

  StreamController<BetterPlayerController> betterPlayerControllerStreamController = StreamController.broadcast();
  BetterPlayerController controller;
  double _visibleFraction = 0.0;
  bool _initialized = false;
  Timer _timer;

  PostItemProvider postItemProvider;

  @override
  void initState() {
    super.initState();

    postItemProvider = Provider.of<PostItemProvider>(context, listen: false);

    WidgetsBinding.instance.addPostFrameCallback((_) {
      if(widget.isSinglePost) _setupController();
    });
  }

  @override
  void dispose() {
    betterPlayerControllerStreamController.close();
    super.dispose();
  }

  @override
  void deactivate() {
    if (controller != null) {
      widget.videoData.wasPlaying = controller.isPlaying();
    }
    _initialized = true;
    _freeController();
    super.deactivate();
  }

  void _setupController() {

    if (controller == null) {

      controller = widget.videoListController.getBetterPlayerController();
      controller.setupDataSource(BetterPlayerDataSource.network(
        widget.videoData.videoFileUrl,
        cacheConfiguration: BetterPlayerCacheConfiguration(
          useCache: true
        )
      ));
      controller.setOverriddenAspectRatio(widget.ratio);

      if (widget.muteVideoPostAtStart) controller.setVolume(0.0);

      betterPlayerControllerStreamController.add(controller);
      controller.addEventsListener(onPlayerEvent);

    }

  }

  void _freeController() {

    if (!_initialized) {
      _initialized = true; return;
    }

    if (controller != null && _initialized) {
      controller.removeEventsListener(onPlayerEvent);
      widget.videoListController.freeBetterPlayerController(controller);
      controller.pause();
      controller = null;
      betterPlayerControllerStreamController.add(null);
      _initialized = false;
    }

  }

  void onPlayerEvent(BetterPlayerEvent event) {
    if (event.betterPlayerEventType == BetterPlayerEventType.progress) {
      widget.videoData.lastPosition = event.parameters["progress"] as Duration;
    }
    if (event.betterPlayerEventType == BetterPlayerEventType.initialized) {
      if (widget.videoData.lastPosition != null) {
        controller.seekTo(widget.videoData.lastPosition);
      }
      if (widget.videoData.wasPlaying) {
        controller.play();
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          VisibilityDetector(
            key: Key(hashCode.toString() + DateTime.now().toString()),
            onVisibilityChanged: (info) {
              _visibleFraction = info.visibleFraction;
              if (!widget.canBuildVideo()) {
                _timer?.cancel();
                _timer = null;
                _timer = Timer(Duration(milliseconds: 500), () {
                  if (info.visibleFraction >= 0.6) {
                    _setupController();
                  } else {
                    _freeController();
                  }
                });
                return;
              }
              if (info.visibleFraction >= 0.6) {
                _setupController();
              } else {
                _freeController();
              }
            },
            child: StreamBuilder<BetterPlayerController>(
              stream: betterPlayerControllerStreamController.stream,
              builder: (context, snapshot) {

                if (!snapshot.hasData || snapshot.hasError){
                  return Container(
                    height: widget.finalHeight,
                    width: widget.finalWidth,
                    color: Colors.black,
                    child: _visibleFraction >= 0.6 ? Center(
                      child: CircularProgressIndicator(
                          valueColor: new AlwaysStoppedAnimation<Color>(Colors.white)
                      ),
                    ) : PostVideoContentPreview(
                        widget.videoData.videoFileUrl,
                        widget.videoData.videoThumbnailUrl,
                        widget.finalHeight,
                        widget.finalWidth,
                        _freeController,
                        _setupController
                    ),
                  );
                }

                return controller != null
                    ? BetterPlayer(controller: controller)
                    : Container(
                        height: widget.finalHeight,
                        width: widget.finalWidth,
                        color: Colors.black,
                        child: PostVideoContentPreview(
                          widget.videoData.videoFileUrl,
                          widget.videoData.videoThumbnailUrl,
                          widget.finalHeight,
                          widget.finalWidth,
                          _freeController,
                          _setupController
                        ),
                      );

              },
            ),
          ),
        ],
      ),
    );
  }
}
```

**Expected behavior**
I expected that the videos that are visible would play normally and that the first video in the list would not appear in the place of the others when the others are visible.

**Flutter doctor**
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [version 10.0.19042.804])
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

**Better Player version**
- Version: 0.0.61

**Smartphone (please complete the following information):**
 - Device: HUAWEI P smart 2019
 - OS: Android

**Comment by jhomlala** [comment]
Fixed in 0.0.63,
