### ISSUE TITLE
[BUG]When the network video file is encrypted and redirected, the video type cannot be obtained

### ISSUE THREAD

**Issue by peterbyCom** [jhomlala/betterplayer#371]
I encountered a problem.

If the network address does not have a suffix, such as MP4, m3u8, it cannot be played.

It returns the file stream through token verification and does not contain the real path address.

Why can't I play?

E/ExoPlayerImplInternal( 4967): Playback error
E/ExoPlayerImplInternal( 4967):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal( 4967):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal( 4967):       at android.os.Handler.dispatchMessage(Handler.java:103)
E/ExoPlayerImplInternal( 4967):       at android.os.Looper.loop(Looper.java:224)
E/ExoPlayerImplInternal( 4967):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 4967):   Caused by: com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (FlvExtractor, FlacExtractor, WavExtractor, FragmentedMp4Extractor, Mp4Extractor, AmrExtractor, PsExtractor, OggExtractor, TsExtractor, MatroskaExtractor, AdtsExtractor, Ac3Extractor, Ac4Extractor, Mp3Extractor, JpegExtractor) could read the stream.

**Comment by peterbyCom** [comment]
https://github.com/jhomlala/betterplayer/issues/250

I checked, done.
