### ISSUE TITLE
[BUG] Error when trying play mpd video file with header include

### ISSUE THREAD

**Issue by ShaggyGettu** [jhomlala/betterplayer#377]
**Describe the bug**
Error when trying play mpd video file with header included.

When adding my token to BetterPlayerDataSource class :
```
dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      url,
      videoFormat: BetterPlayerVideoFormat.dash,
      drmConfiguration: BetterPlayerDrmConfiguration(
        drmType: BetterPlayerDrmType.token,
        token: "token=$token",
      ),
    );
```
and chossing videoFormat 'dash' The video is not playing and throwing exceptions like this:

```
Playback error
E/ExoPlayerImplInternal(14784):   com.google.android.exoplayer2.ExoPlaybackException: Source error
E/ExoPlayerImplInternal(14784):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:579)
E/ExoPlayerImplInternal(14784):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal(14784):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal(14784):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal(14784):   Caused by: com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT token does n...@1:27 in java.io.InputStreamReader@4daae94)
```

**Example code**
Paste here your minimal reproducible code. This code should be ready to copy-paste-run.

```
import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';

void main() => runApp(VideoApp());

class VideoApp extends StatefulWidget {
  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  String url = 'https://dash.akamaized.net/digitalprimates/fraunhofer/480p_video/heaac_2_0_with_video/Sintel/sintel_480p_heaac2_0.mpd';
  String token = 'Token';
  BetterPlayerController _betterPlayerController;
  BetterPlayerDataSource dataSource;

  @override
  void initState() {
    super.initState();
    dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      url,
      videoFormat: BetterPlayerVideoFormat.dash,
      drmConfiguration: BetterPlayerDrmConfiguration(
        drmType: BetterPlayerDrmType.token,
        token: "token=$token",
      ),
    );

    _betterPlayerController = BetterPlayerController(
        BetterPlayerConfiguration(),
        betterPlayerDataSource: dataSource);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Demo',
      home: Scaffold(
        body: Center(
            child: AspectRatio(
          aspectRatio: 16 / 9,
          child: BetterPlayer(
            controller: _betterPlayerController,
          ),
        )),
      ),
    );
  }

  @override
  void dispose() {
    super.dispose();
  }
}

```

**Expected behavior**

Run the video.

**Better Player version**
- Version:  ^0.0.61

**Smartphone (please complete the following information):**
 - Nexus 5
 - Android 30

**Comment by jhomlala** [comment]
Everything works fine on my side and video is loading correctly. Just remember that you need to provide format only if your url doesn't have extension (like mpd or mp4). In your case it's not needed.
