### ISSUE TITLE
[BUG]: network video can't be played 

### ISSUE THREAD

**Issue by marcoberetta96** [jhomlala/betterplayer#434]
**History check**
No similar issue found.

**Describe the bug**
The video can't be played.
A message `Video can't be played is shown`.
Everything is working ok when downloading the video and reproducing it.

Here the log:
```
E/ExoPlayerImplInternal( 7767): Playback error
E/ExoPlayerImplInternal( 7767):   com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640034, -1, null, [1052, 2160, 59.63194], [-1, -1]), format_supported=YES
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:554)
E/ExoPlayerImplInternal( 7767):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 7767):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 7767):       at android.os.HandlerThread.run(HandlerThread.java:67)
E/ExoPlayerImplInternal( 7767):   Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1392)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:839)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:947)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:477)
E/ExoPlayerImplInternal( 7767):       ... 3 more
E/ExoPlayerImplInternal( 7767):   Caused by: android.media.MediaCodec$CodecException: Error 0x1
E/ExoPlayerImplInternal( 7767):       at android.media.MediaCodec.native_queueInputBuffer(Native Method)
E/ExoPlayerImplInternal( 7767):       at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2559)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:119)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1349)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:826)
E/ExoPlayerImplInternal( 7767):       ... 5 more
E/FMQ     ( 7767): grantorIdx must be less than 3
E/MediaCodec( 7767): Codec reported err 0x80000000, actionCode 0, while in state 7
D/SurfaceUtils( 7767): disconnecting from surface 0x7be0a69900, reason disconnectFromSurface
D/PipelineWatcher( 7767): onInputBufferReleased: frameIndex not found (8); ignored
W/MediaCodec( 7767): received FlushCompleted message in state 0
E/ExoPlayerImplInternal( 7767): Disable failed.
E/ExoPlayerImplInternal( 7767):   android.media.MediaCodec$CodecException: Error 0x80000000
E/ExoPlayerImplInternal( 7767):       at android.media.MediaCodec.native_flush(Native Method)
E/ExoPlayerImplInternal( 7767):       at android.media.MediaCodec.flush(MediaCodec.java:2298)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.flush(SynchronousMediaCodecAdapter.java:142)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:887)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:880)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:741)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:482)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:175)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1607)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:1349)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:1313)
E/ExoPlayerImplInternal( 7767):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:570)
E/ExoPlayerImplInternal( 7767):       at android.os.Handler.dispatchMessage(Handler.java:102)
E/ExoPlayerImplInternal( 7767):       at android.os.Looper.loop(Looper.java:223)
E/ExoPlayerImplInternal( 7767):       at android.os.HandlerThread.run(HandlerThread.java:67)

E/flutter (15214): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640034, -1, null, [1052, 2160, 59.63194], [-1, -1]), format_supported=YES, null, null)
```

**Example code*
```
BetterPlayerConfiguration configuration = BetterPlayerConfiguration(fit: BoxFit.scaleDown, looping: false);
return BetterPlayer.network(widget.url, betterPlayerConfiguration: configuration);
```

**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /home/marco/snap/flutter/common/flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /mnt/DATA/Utils/Sdk/
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /mnt/DATA/Utils/Sdk/
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Pixel 3a (mobile) • 948AY0KK49 • android-arm64 • Android 11 (API 30)
    • Linux (desktop)   • linux      • linux-x64     • Linux
```

**Better Player version**
- Version: 0.0.64

**Comment by jhomlala** [comment]
Seems like something with DRM: https://github.com/google/ExoPlayer/issues/7671
Can you share url of the video?

**Comment by marcoberetta96** [comment]
Hi and thanks for your replay.
I've actually realised that the URL does not support hls, so I think that's the problem.
