### ISSUE TITLE
[BUG] Unable to seek before play

### ISSUE THREAD

**Issue by kxmatejka** [jhomlala/betterplayer#454]
**Describe the bug**
If `seekTo` is called immediately before `play`, then it throws an error.

```
E/flutter (30869): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
E/flutter (30869): #0      VideoPlayerController.seekTo (package:better_player/src/video_player/video_player.dart:518:35)
E/flutter (30869): #1      BetterPlayerController.seekTo (package:better_player/src/core/better_player_controller.dart:555:34)
E/flutter (30869): #2      _TivioPlayerState.openAndPlay (package:tivio_sdk/player/tivio_player.dart:147:29)
E/flutter (30869): #3      TivioPlayerWrapper.register.<anonymous closure> (package:tivio_sdk/player/tivio_player_wrapper.dart:67:37)
E/flutter (30869): #4      CallbackMessageBroker.publish (package:tivio_sdk/message_broker.dart:30:21)
E/flutter (30869): #5      Bridge.init.<anonymous closure> (package:tivio_sdk/bridge.dart:65:36)
E/flutter (30869): #6      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (30869): #7      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (30869): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (30869): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (30869): #10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (30869): #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (30869): #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (30869): #13     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (30869): #14     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (30869): #15     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (30869): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (30869): #17     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (30869): #18     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (30869): #19     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (30869): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (30869): #21     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (30869): #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Example code**
```
var config = BetterPlayerConfiguration(
    aspectRatio: 16 / 9,
    fit: BoxFit.contain,
    autoPlay: false,
    autoDispose: true,
    controlsConfiguration: BetterPlayerControlsConfiguration(
      enableOverflowMenu: false,
      enableSkips: false,
    ),
    eventListener: (event) => handleBetterPlayerEvent(event));

var source = BetterPlayerDataSource(
  BetterPlayerDataSourceType.network,
  uri,
);

_betterPlayerController = BetterPlayerController(config);
_betterPlayerController.setupDataSource(source);

_betterPlayerController.seekTo(Duration(milliseconds: 10000));
_betterPlayerController.play();
```

**Expected behavior**
It should seek to 10s and starts playing.

**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_US.UTF-8)
    • Flutter version 2.0.4 at /home/ubuntu/snap/flutter/common/flutter
    • Framework revision b1395592de (4 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/ubuntu/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /home/ubuntu/Android/Sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.10+9-Ubuntu-0ubuntu1.20.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup
      for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at
      /home/ubuntu/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57
    • Flutter plugin version 55.1.3
    • Dart plugin version 203.8147

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android
      10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google
      Chrome 90.0.4430.85
```

**Better Player version**
- Version: 0.0.65

**Comment by jhomlala** [comment]
@kxmatejka You can seek once video has been initialised. I will add additional check in seek method to prevent issues like this. Right now what you can do is listen to the initialised event and seek once you have received that event.

**Comment by anhnt** [comment]
@jhomlala Thank you for you great work on this lib. I have upgraded to latest version 0.0.65 however the bug is still persisted. It has no prob with android devices, only iOS devices when trying to seek. Please see videos here:
iOS: https://www.loom.com/share/964744ef9f4944d38cbb0a1c255c47c1
android: https://www.loom.com/share/e78a4f6486954953baa236d920b086f1
Thank you

**Comment by kxmatejka** [comment]
@jhomlala Thank you for your advice. Seek after initialization works.
