### ISSUE TITLE
Full Screen video A VideoPlayerController was used after being disposed[BUG]

### ISSUE THREAD

**Issue by dvirgiln** [jhomlala/betterplayer#465]
**History check**
I couldn't find this problem.
** Description **
Problem happens when clicking on the full screen button.

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Container(constraints: BoxConstraints(biggest)):
A VideoPlayerController was used after being disposed.

Once you have called dispose() on a VideoPlayerController, it can no longer be used.
The relevant error-causing widget was: 
  MaterialApp file:///Users/davidvirgil@hollandandbarrett.com/dev/workspace/fitwin/lib/main.dart:43:18
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:195:12)
#3      _VideoPlayerState.didUpdateWidget (package:better_player/src/video_player/video_player.dart:641:27)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4682:57)
...
```

**To Reproduce**
1. Include a video and click on the full screen button. 

**Code*
```
  import 'dart:io';

  import 'package:better_player/better_player.dart';
  import 'package:flutter/material.dart';
  import 'package:flutter/services.dart';

  /*
    Waiting for the http headers to be included as part of the video player network call:
    https://github.com/flutter/plugins/pull/2121
   */
  class VideoWidget extends StatefulWidget {
    File file;
    String url;

    VideoWidget({this.file, this.url});

    @override
    _VideoWidgetState createState() => _VideoWidgetState(file, url);
  }

  class _VideoWidgetState extends State<VideoWidget> {
    File _file;
    String _url;

    _VideoWidgetState(this._file, this._url) {}

    BetterPlayerController _betterPlayerController;
    @override
    void initState() {

      super.initState();

      BetterPlayerConfiguration conf = BetterPlayerConfiguration(
        deviceOrientationsAfterFullScreen: [DeviceOrientation.portraitUp],
          controlsConfiguration: BetterPlayerControlsConfiguration(
              enableSubtitles: false,
              enableOverflowMenu: false,
              enableQualities: false,
              enableSkips: false,
              enablePlaybackSpeed: false,
              enableFullscreen: true,
              enableProgressText: false));
      BetterPlayerDataSource source;
      if(this._file != null){
        source = BetterPlayerDataSource.file(_file.path);
      }
      else{
        source =  BetterPlayerDataSource.network(this._url);
      }
      _betterPlayerController = BetterPlayerController(conf,betterPlayerDataSource: source);
      
    }

    @override
    void dispose() {
      _betterPlayerController.dispose();
      _betterPlayerController = null;
      super.dispose();
    }

    @override
    Widget build(BuildContext context) {
      return Theme(
          // Create a unique theme with "ThemeData"
          data: ThemeData.light().copyWith(platform: TargetPlatform.android ?? Theme.of(context).platform),
          child: BetterPlayer(controller: _betterPlayerController,));
    }
  }

```
![Screenshot_2021-05-03-17-24-34-660_com fitwin](https://user-images.githubusercontent.com/6932080/116904091-2f324580-ac35-11eb-9ec3-8eb652f32a22.jpg)

**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.4 19E266 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at /Users/davidvirgil@hollandandbarrett.com/flutter
    • Framework revision 4d7946a68d (7 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/davidvirgil@hollandandbarrett.com/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/davidvirgil@hollandandbarrett.com/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    ! Xcode 11.4.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • Redmi Note 8T (mobile)             • 138db42b      • android-arm64  • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.93
```

**Better Player version**
- Version: 0.0.65 (latest)

**Smartphone (please complete the following information):**
 -  Redmi Note 8T (mobile)             • 138db42b      • android-arm64  • Android 10 (API 29

**Additional context**
Using other plugins as well it was not working the full screen button.

**Comment by jhomlala** [comment]
@dvirgiln Please provide minimal reproducible code. This one has 2 major flaws: 1. it's not null safety and 2. it's only widget definition without showcase how to use it. If you want me to check your problem, you need to provide code which I can simply copy & run.

**Comment by jhomlala** [comment]
No answer from author. Closed.
