### ISSUE TITLE
[BUG] Player toggling fullscreen mode when switching sources even in version 0.0.66

### ISSUE THREAD

**Issue by kxmatejka** [jhomlala/betterplayer#478]
@jhomlala Hi, really appreciate your effort, but the issue remained in version 0.0.66.
Tested on devices:
- Android 10 (API 29) (emulator)
- Android 11 (OnePlus Nord)

And within examples in betterplayer repository.

Here is a code example with fixed null safety support.

```dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:better_player/better_player.dart';

class BetterPlayerFullscreenIssue extends StatefulWidget {
  createState() => _BetterPlayerFullscreenIssueState();
}

class _BetterPlayerFullscreenIssueState extends State<BetterPlayerFullscreenIssue> {
  final List<String> sources = [
    'https://firebasestorage.googleapis.com/v0/b/tivio-dev.appspot.com/o/assets%2Fstatic%2Fad1.mp4?alt=media',
    'https://firebasestorage.googleapis.com/v0/b/tivio-dev.appspot.com/o/assets%2Fstatic%2Fad2.mp4?alt=media',
    'https://firebasestorage.googleapis.com/v0/b/tivio-dev.appspot.com/o/assets%2Fstatic%2Fad3.mp4?alt=media',
    'https://firebasestorage.googleapis.com/v0/b/tivio-dev.appspot.com/o/assets%2Fstatic%2Fad4.mp4?alt=media',
    'https://firebasestorage.googleapis.com/v0/b/tivio-dev.appspot.com/o/assets%2Fstatic%2Fad5.mp4?alt=media',
  ];
  int lastSourceIndex = 0;
  BetterPlayerController? betterPlayerController;
  Timer? timer;

  @override
  void initState() {
    super.initState();
    startChangingSources();
  }

  void startChangingSources() {
    changeSource();
    timer = Timer.periodic(Duration(seconds: 5), (timer) => changeSource());
  }

  void changeSource() {
    if (betterPlayerController != null) {
      betterPlayerController!.pause();
    }

    var config = BetterPlayerConfiguration(
      aspectRatio: 16 / 9,
      autoPlay: true,
      fullScreenByDefault: true,
      controlsConfiguration: BetterPlayerControlsConfiguration(
        playerTheme: BetterPlayerTheme.material,
      ),
    );

    var source = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      sources[lastSourceIndex],
    );

    setState(() {
      betterPlayerController = BetterPlayerController(config);
      betterPlayerController!.setupDataSource(source);

      lastSourceIndex = (lastSourceIndex >= sources.length - 1) ? 0 : lastSourceIndex + 1;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        child: (betterPlayerController != null)
            ? BetterPlayer(
          controller: betterPlayerController!,
        )
            : null,
      ),
    );
  }

  @override
  void dispose() {
    timer!.cancel();
    betterPlayerController = null;
    super.dispose();
  }
}
```

_Originally posted by @kxmatejka in https://github.com/jhomlala/betterplayer/issues/466#issuecomment-836331567_

**Comment by jhomlala** [comment]
@kxmatejka 
```dart
  setState(() {
      betterPlayerController = BetterPlayerController(config);
      betterPlayerController!.setupDataSource(source);

      lastSourceIndex = (lastSourceIndex >= sources.length - 1) ? 0 : lastSourceIndex + 1;
    });
```
Each time, you're changing video, you're creating new BetterPlayerController. You should re-use same BetterPlayerController to keep full screen property state.

**Comment by kxmatejka** [comment]
@jhomlala Hello, I can confirm that reusing previous controller works, but I have a slightly more complicated use case. Besides of change the source I also need to change playerTheme, because I switch between "ad" and "content" sources.

I tried set the key prop from source url, but that ends with an exception.

```
The following assertion was thrown while finalizing the widget tree:
A VideoPlayerController was used after being disposed.

Once you have called dispose() on a VideoPlayerController, it can no longer be used.
When the exception was thrown, this was the stack: 
#0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
#1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
#2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:195:12)
#3      _BetterPlayerSubtitlesDrawerState.dispose (package:better_player/src/subtitles/better_player_subtitles_drawer.dart:85:10)
#4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4721:11)
...
```

**Comment by appsw** [comment]
@kxmatejka I have encountered the same problem. How did you solve it

**Comment by appsw** [comment]
> @jhomlala您好，我可以确认重用以前的控制器有效，但我有一个稍微复杂的用例。除了改变来源，我还需要改变 playerTheme，因为我在“广告”和“内容”来源之间切换。
> 
> 我还尝试将源 URL 中的 key prop 设置为重置内部状态，但这以异常结束。
> 
> ```
> The following assertion was thrown while finalizing the widget tree:
> A VideoPlayerController was used after being disposed.
> 
> Once you have called dispose() on a VideoPlayerController, it can no longer be used.
> When the exception was thrown, this was the stack: 
> #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:117:9)
> #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:123:6)
> #2      ChangeNotifier.removeListener (package:flutter/src/foundation/change_notifier.dart:195:12)
> #3      _BetterPlayerSubtitlesDrawerState.dispose (package:better_player/src/subtitles/better_player_subtitles_drawer.dart:85:10)
> #4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4721:11)
> ...
> ```

 I have encountered the same problem. How did you solve it
