### ISSUE TITLE
iOS: Failed to load video: Operation Stopped

### ISSUE THREAD

**Issue by gmondragon** [jhomlala/betterplayer#5]
Hello. I've been testing this package and on android it works great. In iOS I have the same problem as with the rest. When trying to read a streaming (IPTV) it gives the following error in console:

> flutter: PlatformException(VideoError, Failed to load video: Operation Stopped, null)
> flutter: #0      BetterPlayerController._initialize (package:better_player/src/core/better_player_controller.dart:132:9)
> <asynchronous suspension>
> #1      BetterPlayerController._setup (package:better_player/src/core/better_player_controller.dart:111:11)
> #2      new BetterPlayerController (package:better_player/src/core/better_player_controller.dart:20:7)
> #3      _PlayerState.initState (package:iptv/player.dart:27:31)
> #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
> #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
> #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
> #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)

I appreciate you can help me.

Regards!

**Comment by leszekkrol** [comment]
Any update?

**Comment by jhomlala** [comment]
What's the format of IPTV stream?

**Comment by jhomlala** [comment]
Close due to no activity. If you still encounter this bug, please create new issue. Please remeber to add flutter doctor output and sample code.
