### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alextekartik** [jhomlala/betterplayer#620]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.
Yes.

**Describe the bug**
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      BetterPlayerController._postControllerEvent (package:better_player/src/core/better_player_controller.dart:1227:38)
#2      BetterPlayerController.exitFullScreen (package:better_player/src/core/better_player_controller.dart:593:5)
#3      _BetterPlayerState._pushFullScreenWidget (package:better_player/src/core/better_player.dart:260:23)
<asynchronous suspension>
#4      _BetterPlayerState.onFullScreenChanged (package:better_player/src/core/better_player.dart:160:7)
<asynchronous suspension>
flutter: /http GET https://api-novostable.dev.novosenso.net/v1/box/2f370cae-5ff0-411c-8aa5-c5b9e978b5f1/live/photo

======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for VideoPlayerController:
setState() or markNeedsBuild() called when widget tree was locked.
```

**To Reproduce**

Unfortunately I don't have good steps to reproduce the issue
It seems to happen at the end of a HLS stream (that lasts 5 mns) while being in full screen mode. I did not touch the screen

Looking at the code I would personally add a `if (!_disposed)` in `_postControllerEvent` for safety. Let me know if you want me to try and perform a pull request.

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-FR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more
      details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
[✓] VS Code (version 1.52.0)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

```

**Better Player version**
- Version: 0.0.72

**Smartphone (please complete the following information):**
 - Device: iPod
 - OS: iOS 14.6

**Comment by jhomlala** [comment]
Your BP widget got refreshed somehow, which triggers dispose. I'll additional check in `postControllerEvent` method, but this won't solve root issue.

**Comment by jhomlala** [comment]
Added check in latest release.

**Comment by jhomlala** [comment]
Added check in latest release.
