### ISSUE TITLE
[BUG] memory issue         looping: true, is crashing the app with 2 videos

### ISSUE THREAD

**Issue by dvird** [jhomlala/betterplayer#622]
```W/hallengebattle(28007): Throwing OutOfMemoryError "Failed to allocate a 32 byte allocation with 0 free bytes and 0B until OOM, target footprint 201326592, growth limit 201326592" (VmSize 32717780 kB, recursive case)
W/hallengebattle(28007): "ExoPlayer:Loader:ProgressiveMediaPeriod" prio=5 tid=66 Runnable
W/hallengebattle(28007):   | group="main" sCount=0 dsCount=0 flags=2 obj=0x12c85660 self=0x7a3bfb2a60
W/hallengebattle(28007):   | sysTid=28265 nice=0 cgrp=default sched=0/0 handle=0x7812d73cc0
W/hallengebattle(28007):   | state=R schedstat=( 540769736 20927864 155 ) utm=51 stm=2 core=5 HZ=100
W/hallengebattle(28007):   | stack=0x7812c70000-0x7812c72000 stackSize=1043KB
W/hallengebattle(28007):   | held mutexes= "mutator lock"(shared held)
W/hallengebattle(28007):   at java.util.Arrays.copyOf(Arrays.java:3136)
W/hallengebattle(28007):   at java.util.Arrays.copyOf(Arrays.java:3106)
W/hallengebattle(28007):   at java.util.ArrayList.grow(ArrayList.java:275)
W/hallengebattle(28007):   at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
W/hallengebattle(28007):   at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
W/hallengebattle(28007):   at java.util.ArrayList.add(ArrayList.java:467)
W/hallengebattle(28007):   at com.android.okhttp.internal.http.OkHeaders.toMultimap(OkHeaders.java:104)
W/hallengebattle(28007):   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:227)
W/hallengebattle(28007):   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:179)
W/hallengebattle(28007):   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:30)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.getResponseHeaders(DefaultHttpDataSource.java:307)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.DefaultDataSource.getResponseHeaders(DefaultDataSource.java:217)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getResponseHeaders(CacheDataSource.java:649)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.StatsDataSource.getResponseHeaders(StatsDataSource.java:107)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:86)
W/hallengebattle(28007):   at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
W/hallengebattle(28007):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/hallengebattle(28007):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/hallengebattle(28007):   at java.lang.Thread.run(Thread.java:923)
W/hallengebattle(28007): "ExoPlayer:Loader:ProgressiveMediaPeriod" prio=5 tid=66 Runnable
W/hallengebattle(28007):   | group="main" sCount=0 dsCount=0 flags=2 obj=0x12c85660 self=0x7a3bfb2a60
W/hallengebattle(28007):   | sysTid=28265 nice=0 cgrp=default sched=0/0 handle=0x7812d73cc0
W/hallengebattle(28007):   | state=R schedstat=( 541447913 20927864 156 ) utm=51 stm=2 core=4 HZ=100
W/hallengebattle(28007):   | stack=0x7812c70000-0x7812c72000 stackSize=1043KB
W/hallengebattle(28007):   | held mutexes= "mutator lock"(shared held)
W/hallengebattle(28007):   at java.util.Arrays.copyOf(Arrays.java:3136)
W/hallengebattle(28007):   at java.util.Arrays.copyOf(Arrays.java:3106)
W/hallengebattle(28007):   at java.util.ArrayList.grow(ArrayList.java:275)
W/hallengebattle(28007):   at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:249)
W/hallengebattle(28007):   at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:241)
W/hallengebattle(28007):   at java.util.ArrayList.add(ArrayList.java:467)
W/hallengebattle(28007):   at com.android.okhttp.internal.http.OkHeaders.toMultimap(OkHeaders.java:104)
W/hallengebattle(28007):   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:227)
W/hallengebattle(28007):   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:179)
W/hallengebattle(28007):   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:30)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.getResponseHeaders(DefaultHttpDataSource.java:307)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.DefaultDataSource.getResponseHeaders(DefaultDataSource.java:217)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.cache.CacheDataSource.getResponseHeaders(CacheDataSource.java:649)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.StatsDataSource.getResponseHeaders(StatsDataSource.java:107)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:86)
W/hallengebattle(28007):   at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
W/hallengebattle(28007):   at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
W/hallengebattle(28007):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/hallengebattle(28007):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/hallengebattle(28007):   at java.lang.Thread.run(Thread.java:923)
I/hallengebattle(28007): Waiting for a blocking GC Alloc
I/hallengebattle(28007): Alloc young concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 192MB/192MB, paused 53us total 23.362ms
```

**Comment by jhomlala** [comment]
https://github.com/jhomlala/betterplayer/issues/641#issuecomment-894697721
