### ISSUE TITLE
Allow self signed SSL to be used for HTTPS assets in configuration options

### ISSUE THREAD

**Issue by dantheman213** [jhomlala/betterplayer#666]
Continuation of this issue https://github.com/flutter/flutter/issues/75995. 

VideoPlayer plugin for Flutter does not allow HTTPS self signed assets to be used. This is an issue on all platforms the plugin supports. This ticket has been open for greater than 6 months it seems clear they don't have any interest in figuring it out.

Please confirm that BetterPlayer has this functionality or if not please enable this as a configuration option when loading the plugin/widget.

**Comment by jhomlala** [comment]
@dantheman213 Did it help you? Probably you won't be able to put that app in GP with this TrustManager bypass, but anyway you will be able to play videos on your app.

**Comment by dantheman213** [comment]
I didn't realize you couldn't submit an app tot he store if it allows self signed certs. Sounds like you will have to just use a signed certificate. The scenario I was thinking about though is if the niche app is talking on a private network to a server identified by an IP address or local custom hostname you will have to come up with an alternate solution as you can't create signed certs on IPs in the private space.

**Comment by jhomlala** [comment]
@dantheman213 Do you still have any issue with BP?

**Comment by jhomlala** [comment]
No response from author. Closing issue. Feel free to answer in this issue and I'll reopen it.

**Comment by SalahAdDin** [comment]
I'm having the same bug right now:
```shell
[+11224 ms] E/ExoPlayerImplInternal(10312): Playback error
[        ] E/ExoPlayerImplInternal(10312):   com.google.android.exoplayer2.ExoPlaybackException: Source error
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
[        ] E/ExoPlayerImplInternal(10312):       at android.os.Handler.dispatchMessage(Handler.java:103)
[        ] E/ExoPlayerImplInternal(10312):       at android.os.Looper.loop(Looper.java:214)
[        ] E/ExoPlayerImplInternal(10312):       at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] E/ExoPlayerImplInternal(10312):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:346)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
[        ] E/ExoPlayerImplInternal(10312):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/ExoPlayerImplInternal(10312):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/ExoPlayerImplInternal(10312):       at java.lang.Thread.run(Thread.java:919)
[        ] E/ExoPlayerImplInternal(10312):   Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:608)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:513)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:339)
[        ] E/ExoPlayerImplInternal(10312):       ... 10 more
[        ] E/ExoPlayerImplInternal(10312):   Caused by: java.security.cert.CertificateException: Chain validation failed
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:721)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:551)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:572)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:617)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:617)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:617)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustMana

```

**Comment by SalahAdDin** [comment]
@jhomlala Yes, I'm having the same bug right now:
```shell
[+11224 ms] E/ExoPlayerImplInternal(10312): Playback error
[        ] E/ExoPlayerImplInternal(10312):   com.google.android.exoplayer2.ExoPlaybackException: Source error
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
[        ] E/ExoPlayerImplInternal(10312):       at android.os.Handler.dispatchMessage(Handler.java:103)
[        ] E/ExoPlayerImplInternal(10312):       at android.os.Looper.loop(Looper.java:214)
[        ] E/ExoPlayerImplInternal(10312):       at android.os.HandlerThread.run(HandlerThread.java:67)
[        ] E/ExoPlayerImplInternal(10312):   Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:346)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:774)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1016)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
[        ] E/ExoPlayerImplInternal(10312):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/ExoPlayerImplInternal(10312):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/ExoPlayerImplInternal(10312):       at java.lang.Thread.run(Thread.java:919)
[        ] E/ExoPlayerImplInternal(10312):   Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:608)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:513)
[        ] E/ExoPlayerImplInternal(10312):       at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:339)
[        ] E/ExoPlayerImplInternal(10312):       ... 10 more
[        ] E/ExoPlayerImplInternal(10312):   Caused by: java.security.cert.CertificateException: Chain validation failed
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:721)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:551)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:572)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:617)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:617)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:617)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
[        ] E/ExoPlayerImplInternal(10312):       at com.android.org.conscrypt.TrustMana

```
