### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by W2YAdmin** [jhomlala/betterplayer#785]
**History check**
I confirm I have checked the issue history and haven't found anything which may solve my issue.

**Describe the bug**
Am using latest version of better player (0.0.77) in my project. While it is working as expected, when I try to use PIP mode the app crashes! 

This is the error in the logcat: (Seems to be related to No interface method getPlayerError())
```
E/AndroidRuntime(21456): FATAL EXCEPTION: main
E/AndroidRuntime(21456): Process: flock.media.entertaintment, PID: 21456
E/AndroidRuntime(21456): java.lang.NoSuchMethodError: No interface method getPlayerError()Lcom/google/android/exoplayer2/ExoPlaybackException; in class Lcom/google/android/exoplayer2/Player; or its super classes (declaration of 'com.google.android.exoplayer2.Player' appears in /data/app/~~XzM3JHNnwOoxXmyfEtDwgw==/flock.media.entertaintment-1KyrTIGqz7t7w4PWL4ybJA==/base.apk)
E/AndroidRuntime(21456): 	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.invalidateMediaSessionPlaybackState(MediaSessionConnector.java:766)
E/AndroidRuntime(21456): 	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.setPlayer(MediaSessionConnector.java:488)
E/AndroidRuntime(21456): 	at com.jhomlala.better_player.BetterPlayer.setupMediaSession(BetterPlayer.java:749)
E/AndroidRuntime(21456): 	at com.jhomlala.better_player.BetterPlayerPlugin.enablePictureInPicture(BetterPlayerPlugin.java:483)
E/AndroidRuntime(21456): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.java:259)
E/AndroidRuntime(21456): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.java:206)
E/AndroidRuntime(21456): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(21456): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime(21456): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/AndroidRuntime(21456): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(21456): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(21456): 	at android.os.Looper.loop(Looper.java:183)
E/AndroidRuntime(21456): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(21456): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21456): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(21456): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/.entertaintmen(21456): Background concurrent copying GC freed 1642(164KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 23MB/47MB, paused 4.237ms total 455.160ms
I/Process (21456): Sending signal. PID: 21456 SIG: 9
Lost connection to device.
```

Happens only when I try to open PIP mode, I have tried using the sample code provided for PIP but same result.

**Example code*
```
import 'dart:async';

import 'package:better_player/better_player.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_video_cast/flutter_video_cast.dart';
import 'package:nexthour/models/video_link.dart';
import 'package:modal_progress_hud_nsn/modal_progress_hud_nsn.dart';

import 'Controllers/custom_controls_widget.dart';

GlobalKey betterPlayerKey = GlobalKey();
final GlobalKey<BetterPlayerPlaylistState> betterPlayerPlaylistStateKey =
    GlobalKey();

class BetterPlayerCustom extends StatefulWidget {
  const BetterPlayerCustom({
    this.urllist,
    this.title,
    this.url,
    this.downloadStatus,
  });
  final List<VideoLink> urllist;
  final String title;
  final String url;
  final int downloadStatus;

  @override
  State<BetterPlayerCustom> createState() => _BetterPlayerCustomState();
}

class _BetterPlayerCustomState extends State<BetterPlayerCustom> {
  BetterPlayerController _betterPlayerController;
  GlobalKey _betterPlayerKey = GlobalKey();

  @override
  void initState() {
    BetterPlayerConfiguration betterPlayerConfiguration =
        BetterPlayerConfiguration(
            aspectRatio: 16 / 9,
            fit: BoxFit.contain,
            autoDetectFullscreenDeviceOrientation: true);
    BetterPlayerDataSource dataSource = BetterPlayerDataSource(
      BetterPlayerDataSourceType.network,
      "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    );
    _betterPlayerController = BetterPlayerController(betterPlayerConfiguration);
    _betterPlayerController.setupDataSource(dataSource);
    _betterPlayerController.setBetterPlayerGlobalKey(_betterPlayerKey);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Picture in Picture player"),
      ),
      body: Column(
        children: [
          const SizedBox(height: 8),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16),
            child: Text(
              "Example which shows how to use PiP.",
              style: TextStyle(fontSize: 16),
            ),
          ),
          AspectRatio(
            aspectRatio: 16 / 9,
            child: BetterPlayer(
              controller: _betterPlayerController,
              key: _betterPlayerKey,
            ),
          ),
          ElevatedButton(
            child: Text("Show PiP"),
            onPressed: () {
              _betterPlayerController.enablePictureInPicture(_betterPlayerKey);
            },
          ),
          ElevatedButton(
            child: Text("Disable PiP"),
            onPressed: () async {
              _betterPlayerController.disablePictureInPicture();
            },
          ),
        ],
      ),
    );
  }
}
```
**Expected behavior**
Should be able to use PIP mode

**Flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version
    10.0.22489.1000], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[X] Chrome - develop for the web (Cannot find Chrome executable at
    .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Android Studio (version 2020.3)
[√] VS Code, 64-bit edition (version 1.61.2)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

**Better Player version**
- Version: 0.0.77

**Smartphone (please complete the following information):**
 - Android Emulator

**Comment by jhomlala** [comment]
@W2YAdmin Are you using other video player plugins within your app? Seems like there's other plugin which uses outdated ExoPlayer plugin.

**Comment by jhomlala** [comment]
Closed due to no activity from author.

**Comment by YasmenElGhandour** [comment]
same issue , yes i use just audio package

 Couldn't find a unique registered media button receiver in the given context.
E/MethodChannel#better_player_channel(27966): Failed to handle method call
E/MethodChannel#better_player_channel(27966): java.lang.IllegalArgumentException: ComponentName does not belong to sessionPackageName. sessionPackageName = com.jhomlala.better_player_example, ComponentName pkg = com.google.android.apps.youtube.music
E/MethodChannel#better_player_channel(27966): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
E/MethodChannel#better_player_channel(27966): 	at android.os.Parcel.createException(Parcel.java:2995)
E/MethodChannel#better_player_channel(27966): 	at android.os.Parcel.readException(Parcel.java:2978)
E/MethodChannel#better_player_channel(27966): 	at android.os.Parcel.readException(Parcel.java:2920)
E/MethodChannel#better_player_channel(27966): 	at android.media.session.ISession$Stub$Proxy.setMediaButtonReceiver(ISession.java:466)
E/MethodChannel#better_player_channel(27966): 	at android.media.session.MediaSession.setMediaButtonReceiver(MediaSession.java:289)
E/MethodChannel#better_player_channel(27966): 	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setMediaButtonReceiver(MediaSessionCompat.java:3965)
E/MethodChannel#better_player_channel(27966): 	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:588)
E/MethodChannel#better_player_channel(27966): 	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:539)
E/MethodChannel#better_player_channel(27966): 	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:503)
E/MethodChannel#better_player_channel(27966): 	at com.jhomlala.better_player.BetterPlayer.setupMediaSession(BetterPlayer.kt:633)
E/MethodChannel#better_player_channel(27966): 	at com.jhomlala.better_player.BetterPlayerPlugin.enablePictureInPicture(BetterPlayerPlugin.kt:411)
E/MethodChannel#better_player_channel(27966): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:193)
E/MethodChannel#better_player_channel(27966): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:138)
E/MethodChannel#better_player_channel(27966): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#better_player_channel(27966): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#better_player_channel(27966): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#better_player_channel(27966): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#better_player_channel(27966): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#better_player_channel(27966): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#better_player_channel(27966): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#better_player_channel(27966): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#better_player_channel(27966): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/MethodChannel#better_player_channel(27966): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#better_player_channel(27966): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#better_player_channel(27966): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/MethodChannel#better_player_channel(27966): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#better_player_channel(27966): 	at com.android.server.media.MediaButtonReceiverHolder.create(MediaButtonReceiverHolder.java:125)
E/MethodChannel#better_player_channel(27966): 	at com.android.server.media.MediaSessionRecord$SessionStub.setMediaButtonReceiver(MediaSessionRecord.java:958)
E/MethodChannel#better_player_channel(27966): 	at android.media.session.ISession$Stub.onTransact(ISession.java:251)
E/MethodChannel#better_player_channel(27966): 	at android.os.Binder.execTransactInternal(Binder.java:1280)
E/MethodChannel#better_player_channel(27966): 	at android.os.Binder.execTransact(Binder.java:1244)
E/MethodChannel#better_player_channel(27966): 
E/flutter (27966): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, ComponentName does not belong to sessionPackageName. sessionPackageName = com.jhomlala.better_player_example, ComponentName pkg = com.google.android.apps.youtube.music, null, java.lang.IllegalArgumentException: ComponentName does not belong to sessionPackageName. sessionPackageName = com.jhomlala.better_player_example, ComponentName pkg = com.google.android.apps.youtube.music
E/flutter (27966): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
E/flutter (27966): 	at android.os.Parcel.createException(Parcel.java:2995)
E/flutter (27966): 	at android.os.Parcel.readException(Parcel.java:2978)
E/flutter (27966): 	at android.os.Parcel.readException(Parcel.java:2920)
E/flutter (27966): 	at android.media.session.ISession$Stub$Proxy.setMediaButtonReceiver(ISession.java:466)
E/flutter (27966): 	at android.media.session.MediaSession.setMediaButtonReceiver(MediaSession.java:289)
E/flutter (27966): 	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.setMediaButtonReceiver(MediaSessionCompat.java:3965)
E/flutter (27966): 	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:588)
E/flutter (27966): 	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:539)
E/flutter (27966): 	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:503)
E/flutter (27966): 	at com.jhomlala.better_player.BetterPlayer.setupMediaSession(BetterPlayer.kt:633)
E/flutter (27966): 	at com.jhomlala.better_player.BetterPlayerPlugin.enablePictureInPicture(BetterPlayerPlugin.kt:411)
E/flutter (27966): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:193)
E/flutter (27966): 	at com.jhomlala.better_player.BetterPlayerPlugin.onMethodCall(BetterPlayerPlugin.kt:138)
E/flutter (27966): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/flutter (27966): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/flutter (27966): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/flutter (27966): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter (27966): 	at android.os.Handler.handleCallback(Handler.java:942)
E/flutter (27966): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter (27966): 	at android.os.Looper.loopOnce(Looper.java:201)
E/flutter (27966): 	at android.os.Looper.loop(Looper.java:288)
E/flutter (27966): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/flutter (27966): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27966): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/flutter (27966): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/flutter (27966): Caused by: android.os.RemoteException: Remote stack trace:
E/flutter (27966): 	at com.android.server.media.MediaButtonReceiverHolder.create(MediaButtonReceiverHolder.java:125)
E/flutter (27966): 	at com.android.server.media.MediaSessionRecord$SessionStub.setMediaButtonReceiver(MediaSessionRecord.java:958)
E/flutter (27966): 	at android.media.session.ISession$Stub.onTransact(ISession.java:251)
E/flutter (27966): 	at android.os.Binder.execTransactInternal(Binder.java:1280)
E/flutter (27966): 	at android.os.Binder.execTransact(Binder.java:1244)
E/flutter (27966): 
E/flutter (27966): )
E/flutter (27966): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (27966): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (27966): <asynchronous suspension>
E/flutter (27966): #2      VideoPlayerController.enablePictureInPicture (package:better_player/src/video_player/video_player.dart:595:5)
E/flutter (27966): <asynchronous suspension>
E/flutter (27966): #3      BetterPlayerController.enablePictureInPicture (package:better_player/src/core/better_player_controller.dart:1085:9)
E/flutter (27966): <asynchronous suspension>
E/flutter (27966):
