### ISSUE TITLE
[BUG]  A VideoPlayerController was used after being disposed

### ISSUE THREAD

**Issue by pavanjoshi914** [jhomlala/betterplayer#839]
**History check**
Please confirm that you've checked issues history and you didn't find anything which may solve your issue.

**Describe the bug**

I am using better_player latest version , I use grid to render videos, on clicking any of the video it takes me to the new widget which renders video using video_player
Following error was thrown
```
       ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
                    The following assertion was thrown while dispatching notifications for VideoPlayerController:
                    setState() or markNeedsBuild() called when widget tree was locked.
                    This BetterPlayerSubtitlesDrawer widget cannot be marked as needing to build because the framework
                    is locked.
                    The widget on which setState() or markNeedsBuild() was called was:
                      BetterPlayerSubtitlesDrawer
                    
                    When the exception was thrown, this was the stack:
                    #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4310:9)
                    #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4320:6)
                    #2      State.setState (package:flutter/src/widgets/framework.dart:1108:15)
                    #3      _BetterPlayerSubtitlesDrawerState._updateState (package:better_player/src/subtitles/better_player_subtitles_drawer.dart:88:7)
                    #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:308:24)
                    #5      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:412:5)
                    #6      VideoPlayerController.pause (package:better_player/src/video_player/video_player.dart:450:5)
                    #7      BetterPlayerController.pause (package:better_player/src/core/better_player_controller.dart:642:34)
                    #8      BetterPlayerController.dispose (package:better_player/src/core/better_player_controller.dart:1270:9)
                    #9      _BetterPlayerState.dispose (package:better_player/src/core/better_player.dart:118:23)
                    #10     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4895:11)
                    #11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1883:13)
                    #12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
                    #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
                    #14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
                    #15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
                    #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
                    #17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
                    #18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
                    #19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
                    #20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
                    #21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
                    #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4719:14)
                    #23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
                    #24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1881:7)
                    #25     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6182:14)
                    #26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1879:13)
                    #27     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
                    #28     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1892:25)
                    #29     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2879:27)
                    #30     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2510:15)
                    #31     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2878:7)
                    #32     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:19)
                    #33     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
                    #34     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
                    #35     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
                    #36     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
                    #40     _invoke (dart:ui/hooks.dart:166:10)
                    #41     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
                    #42     _drawFrame (dart:ui/hooks.dart:129:31)
                    (elided 3 frames from dart:async)
                    
                    The VideoPlayerController sending notification was:
                      VideoPlayerController#b6559(VideoPlayerValue(duration: null, size: null, position: 0:00:00.000000,
                      absolutePosition: null, buffered: [], isPlaying: false, isLooping: false, isBuffering: false,
                      volume: 1.0, errorDescription: null))
                    ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**To Reproduce**
1. 'From grid click on any video - this takes to VideoPlayer Widget
2.  Play video using better_player 
3.  Go back , click on any other video

**Example code*
video_controller
```
class StatusVideo extends StatefulWidget {
    const StatusVideo({
    Key? key,
    required this.videoSrc,

  }) : super(key: key);

  final String videoSrc;


  @override
  _StatusVideoState createState() => _StatusVideoState();
}

class _StatusVideoState extends State<StatusVideo> {

  late BetterPlayerController _betterPlayerController;


  @override
  void initState() {
    super.initState();
    BetterPlayerDataSource betterPlayerDataSource = BetterPlayerDataSource(
        BetterPlayerDataSourceType.file, widget.videoSrc);
    _betterPlayerController =  BetterPlayerController(
        BetterPlayerConfiguration(fit: BoxFit.cover, aspectRatio: 1.0),
        betterPlayerDataSource: betterPlayerDataSource,


        //
        );


  }

  @override
  Widget build(BuildContext context) {
   
    return Hero(
        tag: widget.videoSrc,
        child:  Center(  child:
             BetterPlayer(
              controller: _betterPlayerController,
            )));
    //     ],
    //   ),
    // );
  }

  // it is good to dispose any controller we use for better performance
  // dispose method use to release the memory allocated to variables when state object/ controller is removed.
  @override
  void dispose() {
    _betterPlayerController.dispose();

    super.dispose();
  }

}

```

VideoPlayer
```
Scaffold(
        body: StatusVideo(
           videoSrc:  widget.videoFile,

        ),
)
```

**Flutter doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.22000.318], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)

• No issues found!

```
**Better Player version**
- Version: 0.0.79

**Smartphone (please complete the following information):**
 - Device: vivo 1904
 - OS: android

**Comment by pavanjoshi914** [comment]
Solved! I was using Hero tag  as a wrapper around better player , removing it worked for it
